/* JS */ gapi.loaded_1(function(_){var window=this;
_.he=function(a,b){var c;a:{c=a.length;for(var d=_.ka(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break a}c=-1}return 0>c?null:_.ka(a)?a.charAt(c):a[c]};_.me=function(a,b){for(var c=a.split("."),d=b||_.r,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};_.ne=function(a,b){return 1==_.fd.splice.call(a,b,1).length};_.oe=function(a,b){var c=(0,_.gd)(a,b),d;(d=0<=c)&&_.ne(a,c);return d};
_.pe=function(){this.Vd=this.Vd;this.Za=this.Za};_.pe.prototype.Vd=!1;_.pe.prototype.wb=function(){return this.Vd};_.pe.prototype.ua=function(){this.Vd||(this.Vd=!0,this.ja())};_.re=function(a,b){var c=_.va(_.qe,b);a.Vd?c.call(void 0):(a.Za||(a.Za=[]),a.Za.push(_.ea(void 0)?(0,_.t)(c,void 0):c))};_.pe.prototype.ja=function(){if(this.Za)for(;this.Za.length;)this.Za.shift()()};_.qe=function(a){a&&"function"==typeof a.ua&&a.ua()};
_.se=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.bh=!1;this.fz=!0};_.se.prototype.stopPropagation=function(){this.bh=!0};_.se.prototype.preventDefault=function(){this.defaultPrevented=!0;this.fz=!1};var te=function(a){te[" "](a);return a};te[" "]=_.ce;var ve,we;_.ue=!_.N||9<=_.be;ve=!_.N||9<=_.be;we=_.N&&!_.$d("9");!_.Od||_.$d("528");_.Nd&&_.$d("1.9b")||_.N&&_.$d("8")||_.Ld&&_.$d("9.5")||_.Od&&_.$d("528");_.Nd&&!_.$d("8")||_.N&&_.$d("9");_.xe=_.N?"focusin":"DOMFocusIn";_.ye=_.N?"focusout":"DOMFocusOut";_.ze=_.Od?"webkitTransitionEnd":_.Ld?"otransitionend":"transitionend";_.Ae=function(a,b){_.se.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.charCode=this.keyCode=this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.fn=!1;this.Dc=null;a&&this.lb(a,b)};_.u(_.Ae,_.se);
_.Ae.prototype.lb=function(a,b){var c=this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;var d=a.relatedTarget;if(d){if(_.Nd){var e;a:{try{te(d.nodeName);e=!0;break a}catch(f){}e=!1}e||(d=null)}}else"mouseover"==c?d=a.fromElement:"mouseout"==c&&(d=a.toElement);this.relatedTarget=d;this.offsetX=_.Od||void 0!==a.offsetX?a.offsetX:a.layerX;this.offsetY=_.Od||void 0!==a.offsetY?a.offsetY:a.layerY;this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:
a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.fn=_.Qd?a.metaKey:a.ctrlKey;this.state=a.state;this.Dc=a;a.defaultPrevented&&this.preventDefault()};
_.Ae.prototype.stopPropagation=function(){_.Ae.R.stopPropagation.call(this);this.Dc.stopPropagation?this.Dc.stopPropagation():this.Dc.cancelBubble=!0};_.Ae.prototype.preventDefault=function(){_.Ae.R.preventDefault.call(this);var a=this.Dc;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,we)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};_.Ae.prototype.wF=function(){return this.Dc};
var Be,De;Be="closure_listenable_"+(1E6*Math.random()|0);_.Ce=function(a){return!(!a||!a[Be])};De=0;var Ee=function(a,b,c,d,e){this.listener=a;this.G=null;this.src=b;this.type=c;this.tl=!!d;this.Qc=e;this.key=++De;this.Bi=this.ql=!1},Ge=function(a){a.Bi=!0;a.listener=null;a.G=null;a.src=null;a.Qc=null};var He=function(a){this.src=a;this.G={};this.I=0},Je,Ie;He.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.G[f];a||(a=this.G[f]=[],this.I++);var g=Ie(a,b,d,e);-1<g?(b=a[g],c||(b.ql=!1)):(b=new Ee(b,this.src,f,!!d,e),b.ql=c,a.push(b));return b};He.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.G))return!1;var e=this.G[a];b=Ie(e,b,c,d);return-1<b?(Ge(e[b]),_.ne(e,b),0==e.length&&(delete this.G[a],this.I--),!0):!1};
Je=function(a,b){var c=b.type;c in a.G&&_.oe(a.G[c],b)&&(Ge(b),0==a.G[c].length&&(delete a.G[c],a.I--))};_.Ke=function(a,b,c,d,e){a=a.G[b.toString()];b=-1;a&&(b=Ie(a,c,d,e));return-1<b?a[b]:null};Ie=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.Bi&&f.listener==b&&f.tl==!!c&&f.Qc==d)return e}return-1};
var Le,Me,Ne,Pe,Re,Se,Ye,Xe,Te,Ze;Le="closure_lm_"+(1E6*Math.random()|0);Me={};Ne=0;_.P=function(a,b,c,d,e){if(_.ja(b)){for(var f=0;f<b.length;f++)_.P(a,b[f],c,d,e);return null}c=_.Oe(c);return _.Ce(a)?a.V(b,c,d,e):Pe(a,b,c,!1,d,e)};
Pe=function(a,b,c,d,e,f){if(!b)throw Error("k");var g=!!e,k=_.Qe(a);k||(a[Le]=k=new He(a));c=k.add(b,c,d,e,f);if(c.G)return c;d=Re();c.G=d;d.src=a;d.listener=c;if(a.addEventListener)a.addEventListener(b.toString(),d,g);else if(a.attachEvent)a.attachEvent(Se(b.toString()),d);else throw Error("l");Ne++;return c};Re=function(){var a=Te,b=ve?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b};
_.Ue=function(a,b,c,d,e){if(_.ja(b)){for(var f=0;f<b.length;f++)_.Ue(a,b[f],c,d,e);return null}c=_.Oe(c);return _.Ce(a)?a.Ne.add(String(b),c,!0,d,e):Pe(a,b,c,!0,d,e)};_.Ve=function(a,b,c,d,e){if(_.ja(b))for(var f=0;f<b.length;f++)_.Ve(a,b[f],c,d,e);else c=_.Oe(c),_.Ce(a)?a.Qa(b,c,d,e):a&&(a=_.Qe(a))&&(b=_.Ke(a,b,c,!!d,e))&&_.We(b)};
_.We=function(a){if(!_.Zc(a)&&a&&!a.Bi){var b=a.src;if(_.Ce(b))Je(b.Ne,a);else{var c=a.type,d=a.G;b.removeEventListener?b.removeEventListener(c,d,a.tl):b.detachEvent&&b.detachEvent(Se(c),d);Ne--;(c=_.Qe(b))?(Je(c,a),0==c.I&&(c.src=null,b[Le]=null)):Ge(a)}}};Se=function(a){return a in Me?Me[a]:Me[a]="on"+a};Ye=function(a,b,c,d){var e=!0;if(a=_.Qe(a))if(b=a.G[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.tl==c&&!f.Bi&&(f=Xe(f,d),e=e&&!1!==f)}return e};
Xe=function(a,b){var c=a.listener,d=a.Qc||a.src;a.ql&&_.We(a);return c.call(d,b)};
Te=function(a,b){if(a.Bi)return!0;if(!ve){var c=b||_.me("window.event"),d=new _.Ae(c,this),e=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var f=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(g){f=!0}if(f||void 0==c.returnValue)c.returnValue=!0}c=[];for(f=d.currentTarget;f;f=f.parentNode)c.push(f);for(var f=a.type,k=c.length-1;!d.bh&&0<=k;k--){d.currentTarget=c[k];var l=Ye(c[k],f,!0,d),e=e&&l}for(k=0;!d.bh&&k<c.length;k++)d.currentTarget=c[k],l=Ye(c[k],f,!1,d),e=e&&l}return e}return Xe(a,new _.Ae(b, this))};_.Qe=function(a){a=a[Le];return a instanceof He?a:null};Ze="__closure_events_fn_"+(1E9*Math.random()>>>0);_.Oe=function(a){if(_.Yc(a))return a;a[Ze]||(a[Ze]=function(b){return a.handleEvent(b)});return a[Ze]};_.ge(function(a){Te=a(Te)});
_.$e=function(){_.pe.call(this);this.Ne=new He(this);this.Sn=this;this.Ce=null};_.u(_.$e,_.pe);_.$e.prototype[Be]=!0;_.h=_.$e.prototype;_.h.Vh=function(){return this.Ce};_.h.ih=_.q(1);_.h.addEventListener=function(a,b,c,d){_.P(this,a,b,c,d)};_.h.removeEventListener=function(a,b,c,d){_.Ve(this,a,b,c,d)};
_.h.dispatchEvent=function(a){var b,c=this.Vh();if(c)for(b=[];c;c=c.Vh())b.push(c);var c=this.Sn,d=a.type||a;if(_.ka(a))a=new _.se(a,c);else if(a instanceof _.se)a.target=a.target||c;else{var e=a;a=new _.se(d,c);_.Gd(a,e)}var e=!0,f;if(b)for(var g=b.length-1;!a.bh&&0<=g;g--)f=a.currentTarget=b[g],e=af(f,d,!0,a)&&e;a.bh||(f=a.currentTarget=c,e=af(f,d,!0,a)&&e,a.bh||(e=af(f,d,!1,a)&&e));if(b)for(g=0;!a.bh&&g<b.length;g++)f=a.currentTarget=b[g],e=af(f,d,!1,a)&&e;return e};
_.h.ja=function(){_.$e.R.ja.call(this);if(this.Ne){var a=this.Ne,b=0,c;for(c in a.G){for(var d=a.G[c],e=0;e<d.length;e++)++b,Ge(d[e]);delete a.G[c];a.I--}}this.Ce=null};_.h.V=function(a,b,c,d){return this.Ne.add(String(a),b,!1,c,d)};_.h.Qa=function(a,b,c,d){return this.Ne.remove(String(a),b,c,d)}; var af=function(a,b,c,d){b=a.Ne.G[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.Bi&&g.tl==c){var k=g.listener,l=g.Qc||g.src;g.ql&&Je(a.Ne,g);e=!1!==k.call(l,d)&&e}}return e&&0!=d.fz};

var bf;bf=function(a){var b=arguments.length;if(1==b&&_.ja(arguments[0]))return bf.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};_.cf=bf("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));
_.ef=function(){this.G="";this.I=_.df};_.ef.prototype.Vg=!0;_.df={};_.ef.prototype.Yd=_.q(4);_.ff=function(a){var b=new _.ef;b.G=a;return b};_.gf=_.ff("");_.jf=function(){this.G="";this.J=_.hf;this.I=null};_.jf.prototype.Gq=!0;_.jf.prototype.wf=_.q(6);_.jf.prototype.Vg=!0;_.jf.prototype.Yd=_.q(3);_.hf={};_.kf=function(a,b){var c=new _.jf;c.G=a;c.I=b;return c};_.kf("<!DOCTYPE html>",0);_.lf=_.kf("",0);
_.mf=function(a){if("function"==typeof a.Gc)return a.Gc();if(_.ka(a))return a.split("");if(_.Uc(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return _.sd(a)};_.nf=function(a){if("function"==typeof a.qd)return a.qd();if("function"!=typeof a.Gc){if(_.Uc(a)||_.ka(a)){var b=[];a=a.length;for(var c=0;c<a;c++)b.push(c);return b}return _.td(a)}}; _.of=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(_.Uc(a)||_.ka(a))(0,_.id)(a,b,c);else for(var d=_.nf(a),e=_.mf(a),f=e.length,g=0;g<f;g++)b.call(c,e[g],d&&d[g],a)};

_.pf=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,_.wa)()).toString(36)};_.qf="StopIteration"in _.r?_.r.StopIteration:{message:"StopIteration",stack:""};_.rf=function(){};_.rf.prototype.next=function(){throw _.qf;};_.rf.prototype.of=function(){return this};
_.sf=function(a,b){this.I={};this.G=[];this.M=this.K=0;var c=arguments.length;if(1<c){if(c%2)throw Error("j");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof _.sf?(c=a.qd(),d=a.Gc()):(c=_.td(a),d=_.sd(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};_.h=_.sf.prototype;_.h.ob=function(){return this.K};_.h.Gc=function(){tf(this);for(var a=[],b=0;b<this.G.length;b++)a.push(this.I[this.G[b]]);return a};_.h.qd=function(){tf(this);return this.G.concat()};_.h.Fh=_.q(7);
_.h.equals=function(a,b){if(this===a)return!0;if(this.K!=a.ob())return!1;var c=b||uf;tf(this);for(var d,e=0;d=this.G[e];e++)if(!c(this.get(d),a.get(d)))return!1;return!0};var uf=function(a,b){return a===b};_.sf.prototype.isEmpty=function(){return 0==this.K};_.sf.prototype.clear=function(){this.I={};this.M=this.K=this.G.length=0};_.sf.prototype.remove=function(a){return _.vf(this.I,a)?(delete this.I[a],this.K--,this.M++,this.G.length>2*this.K&&tf(this),!0):!1};
var tf=function(a){if(a.K!=a.G.length){for(var b=0,c=0;b<a.G.length;){var d=a.G[b];_.vf(a.I,d)&&(a.G[c++]=d);b++}a.G.length=c}if(a.K!=a.G.length){for(var e={},c=b=0;b<a.G.length;)d=a.G[b],_.vf(e,d)||(a.G[c++]=d,e[d]=1),b++;a.G.length=c}};_.h=_.sf.prototype;_.h.get=function(a,b){return _.vf(this.I,a)?this.I[a]:b};_.h.set=function(a,b){_.vf(this.I,a)||(this.K++,this.G.push(a),this.M++);this.I[a]=b};
_.h.forEach=function(a,b){for(var c=this.qd(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};_.h.clone=function(){return new _.sf(this)};_.h.of=function(a){tf(this);var b=0,c=this.M,d=this,e=new _.rf;e.next=function(){if(c!=d.M)throw Error("u");if(b>=d.G.length)throw _.qf;var e=d.G[b++];return a?e:d.I[e]};return e};_.vf=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};

var xf,yf;_.sf.prototype.Fh=_.M(7,function(a){for(var b=0;b<this.G.length;b++){var c=this.G[b];if(_.vf(this.I,c)&&this.I[c]==a)return!0}return!1});_.wf=function(a){var b=0,c;for(c in a)b++;return b};xf=function(a,b){if("function"==typeof a.every)return a.every(b,void 0);if(_.Uc(a)||_.ka(a))return(0,_.md)(a,b,void 0);for(var c=_.nf(a),d=_.mf(a),e=d.length,f=0;f<e;f++)if(!b.call(void 0,d[f],c&&c[f],a))return!1;return!0};yf=function(a){return"function"==typeof a.ob?a.ob():_.Uc(a)||_.ka(a)?a.length:_.wf(a)};
var Bf;_.zf=function(a){this.G=new _.sf;if(a){a=_.mf(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])}};Bf=function(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+_.Wc(a):b.substr(0,1)+a};_.h=_.zf.prototype;_.h.ob=function(){return this.G.ob()};_.h.add=function(a){this.G.set(Bf(a),a)};_.h.remove=function(a){return this.G.remove(Bf(a))};_.h.clear=function(){this.G.clear()};_.h.isEmpty=function(){return this.G.isEmpty()};_.h.contains=function(a){a=Bf(a);return _.vf(this.G.I,a)};_.h.Gc=function(){return this.G.Gc()};
_.h.clone=function(){return new _.zf(this)};_.h.equals=function(a){return this.ob()==yf(a)&&Cf(this,a)};var Cf=function(a,b){var c=yf(b);if(a.ob()>c)return!1;!("undefined"!=typeof _.zf&&b instanceof _.zf)&&5<c&&(b=new _.zf(b));return xf(a,function(a){var c=b;return"function"==typeof c.contains?c.contains(a):"function"==typeof c.Fh?c.Fh(a):_.Uc(c)||_.ka(c)?_.nd(c,a):_.ud(c,a)})};_.zf.prototype.of=function(){return this.G.of(!1)};

var ih,nh,ph,qh,oh;ih=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))};_.jh=function(a){a=String(a);if(ih(a))try{return eval("("+a+")")}catch(b){}throw Error("v`"+a);};_.mh=function(a){return _.kh(new _.lh(void 0),a)};_.lh=function(a){this.G=a};_.kh=function(a,b){var c=[];nh(a,b,c);return c.join("")};
nh=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(_.ja(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),e=d[f],nh(a,a.G?a.G.call(d,String(f),e):e,c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");f="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(e=b[d],"function"!=typeof e&&(c.push(f),oh(d,c),c.push(":"),nh(a,a.G?a.G.call(b,d,e):e,c),f=","));c.push("}");return}}switch(typeof b){case "string":oh(b,
c);break;case "number":c.push((0,window.isFinite)(b)&&!(0,window.isNaN)(b)?b:"null");break;case "boolean":c.push(b);break;case "function":c.push("null");break;default:throw Error("w`"+typeof b);}}};ph={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"};qh=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g; oh=function(a,b){b.push('"',a.replace(qh,function(a){var b=ph[a];b||(b="\\u"+(a.charCodeAt(0)|65536).toString(16).substr(1),ph[a]=b);return b}),'"')};

_.rh=function(a,b){_.$e.call(this);this.I=a||1;this.G=b||_.r;this.J=(0,_.t)(this.vL,this);this.K=(0,_.wa)()};_.u(_.rh,_.$e);_.h=_.rh.prototype;_.h.enabled=!1;_.h.Zd=null;_.h.setInterval=function(a){this.I=a;this.Zd&&this.enabled?(_.sh(this),this.start()):this.Zd&&_.sh(this)};
_.h.vL=function(){if(this.enabled){var a=(0,_.wa)()-this.K;0<a&&a<.8*this.I?this.Zd=this.G.setTimeout(this.J,this.I-a):(this.Zd&&(this.G.clearTimeout(this.Zd),this.Zd=null),this.dispatchEvent("tick"),this.enabled&&(this.Zd=this.G.setTimeout(this.J,this.I),this.K=(0,_.wa)()))}};_.h.start=function(){this.enabled=!0;this.Zd||(this.Zd=this.G.setTimeout(this.J,this.I),this.K=(0,_.wa)())};_.sh=function(a){a.enabled=!1;a.Zd&&(a.G.clearTimeout(a.Zd),a.Zd=null)};
_.rh.prototype.ja=function(){_.rh.R.ja.call(this);_.sh(this);delete this.G};_.th=function(a,b,c){if(_.Yc(a))c&&(a=(0,_.t)(a,c));else if(a&&"function"==typeof a.handleEvent)a=(0,_.t)(a.handleEvent,a);else throw Error("x");return 2147483647<b?-1:_.r.setTimeout(a,b||0)};_.uh=function(a){_.r.clearTimeout(a)};

_.Fh=function(a){switch(a){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:return!0;default:return!1}};_.Gh=function(a){return eval("("+a+")")};_.Hh=function(a,b,c){a=a.split(b);for(var d=[];0<c&&a.length;)d.push(a.shift()),c--;a.length&&d.push(a.join(b));return d};
var Ih=function(){};Ih.prototype.G=null;var Kh=function(a){var b;(b=a.G)||(b={},Jh(a)&&(b[0]=!0,b[1]=!0),b=a.G=b);return b};var Mh,Jh;Mh=function(){};_.u(Mh,Ih);_.Nh=function(a){return(a=Jh(a))?new window.ActiveXObject(a):new window.XMLHttpRequest};Jh=function(a){if(!a.I&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.I=d}catch(e){}}throw Error("y");}return a.I};_.Lh=new Mh;
var Ph,Qh,Rh;_.Oh=function(a){_.$e.call(this);this.headers=new _.sf;this.ma=a||null;this.I=!1;this.T=this.G=null;this.Y="";this.M=0;this.J=this.ha=this.S=this.W=!1;this.O=0;this.U=null;this.K="";this.wa=this.ya=!1};_.u(_.Oh,_.$e);Ph=/^https?$/i;Qh=["POST","PUT"];Rh=[];_.Sh=function(a,b,c,d,e,f){var g=new _.Oh;Rh.push(g);b&&g.V("complete",b);g.Ne.add("ready",g.Fa,!0,void 0,void 0);f&&(g.O=Math.max(0,f));g.send(a,c,d,e)};_.Oh.prototype.Fa=function(){this.ua();_.oe(Rh,this)};_.Oh.prototype.Zp=function(){return this.K};
_.Oh.prototype.send=function(a,b,c,d){if(this.G)throw Error("z`"+this.Y+"`"+a);b=b?b.toUpperCase():"GET";this.Y=a;this.M=0;this.W=!1;this.I=!0;this.G=this.ma?_.Nh(this.ma):_.Nh(_.Lh);this.T=this.ma?Kh(this.ma):Kh(_.Lh);this.G.onreadystatechange=(0,_.t)(this.Ca,this);try{this.ha=!0,this.G.open(b,String(a),!0),this.ha=!1}catch(e){Th(this);return}a=c||"";var f=this.headers.clone();d&&_.of(d,function(a,b){f.set(b,a)});d=_.he(f.qd(),Uh);c=_.r.FormData&&a instanceof _.r.FormData;!_.nd(Qh,b)||d||c||f.set("Content-Type",
"application/x-www-form-urlencoded;charset=utf-8");f.forEach(function(a,b){this.G.setRequestHeader(b,a)},this);this.K&&(this.G.responseType=this.K);"withCredentials"in this.G&&(this.G.withCredentials=this.ya);try{Vh(this),0<this.O&&((this.wa=Wh(this.G))?(this.G.timeout=this.O,this.G.ontimeout=(0,_.t)(this.jd,this)):this.U=_.th(this.jd,this.O,this)),this.S=!0,this.G.send(a),this.S=!1}catch(g){Th(this)}};
var Wh=function(a){return _.N&&_.$d(9)&&_.Zc(a.timeout)&&_.ea(a.ontimeout)},Uh=function(a){return"content-type"==a.toLowerCase()};_.Oh.prototype.jd=function(){"undefined"!=typeof _.da&&this.G&&(this.M=8,this.dispatchEvent("timeout"),this.abort(8))};var Th=function(a){a.I=!1;a.G&&(a.J=!0,a.G.abort(),a.J=!1);a.M=5;Xh(a);Yh(a)},Xh=function(a){a.W||(a.W=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))};
_.Oh.prototype.abort=function(a){this.G&&this.I&&(this.I=!1,this.J=!0,this.G.abort(),this.J=!1,this.M=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Yh(this))};_.Oh.prototype.ja=function(){this.G&&(this.I&&(this.I=!1,this.J=!0,this.G.abort(),this.J=!1),Yh(this,!0));_.Oh.R.ja.call(this)};_.Oh.prototype.Ca=function(){this.wb()||(this.ha||this.S||this.J?Zh(this):this.la())};_.Oh.prototype.la=function(){Zh(this)};
var Zh=function(a){if(a.I&&"undefined"!=typeof _.da&&(!a.T[1]||4!=_.$h(a)||2!=a.getStatus()))if(a.S&&4==_.$h(a))_.th(a.Ca,0,a);else if(a.dispatchEvent("readystatechange"),4==_.$h(a)){a.I=!1;try{_.ai(a)?(a.dispatchEvent("complete"),a.dispatchEvent("success")):(a.M=6,a.getStatus(),Xh(a))}finally{Yh(a)}}},Yh=function(a,b){if(a.G){Vh(a);var c=a.G,d=a.T[0]?_.ce:null;a.G=null;a.T=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},Vh=function(a){a.G&&a.wa&&(a.G.ontimeout=null);_.Zc(a.U)&&
(_.uh(a.U),a.U=null)};_.Oh.prototype.Jc=function(){return!!this.G};_.ai=function(a){var b=a.getStatus(),c;if(!(c=_.Fh(b))){if(b=0===b)a=_.Ah(String(a.Y))[1]||null,!a&&_.r.self&&_.r.self.location&&(a=_.r.self.location.protocol,a=a.substr(0,a.length-1)),b=!Ph.test(a?a.toLowerCase():"");c=b}return c};_.$h=function(a){return a.G?a.G.readyState:0};_.Oh.prototype.getStatus=function(){try{return 2<_.$h(this)?this.G.status:-1}catch(a){return-1}};_.bi=function(a){try{return a.G?a.G.responseText:""}catch(b){return""}};
_.ci=function(a){try{if(!a.G)return null;if("response"in a.G)return a.G.response;switch(a.K){case "":case "text":return a.G.responseText;case "arraybuffer":if("mozResponseArrayBuffer"in a.G)return a.G.mozResponseArrayBuffer}return null}catch(b){return null}};_.Oh.prototype.getAllResponseHeaders=function(){return this.G&&4==_.$h(this)?this.G.getAllResponseHeaders():""};_.ge(function(a){_.Oh.prototype.la=a(_.Oh.prototype.la)});

var Dk;_.Bk=function(a){if(!_.Uc(a))return null;for(var b={},c=0;c<a.length;c++)b[a[c]]=a[c];return b};_.Ck=function(a,b){var c=a.length;if(c!=b.length)return!1;for(var d=0;d<c;++d){var e=a.charCodeAt(d),f=b.charCodeAt(d);65<=e&&90>=e&&(e+=32);65<=f&&90>=f&&(f+=32);if(e!=f)return!1}return!0};Dk=null;
_.Ek=function(a){if(null===Dk){var b=_.E("client/headers/response");b||(b=_.E("googleapis/headers/response"));Dk=_.Bk(b)}if(null!=Dk){if(Dk.hasOwnProperty(a))return!0;for(var c in Dk)if(Dk.hasOwnProperty(c)&&_.Ck(c,a))return!0}return!1};
_.Fk=function(a){a=String(a||"").split("\x00").join("");for(var b=[],c=!0,d=0,e=a.length;d<e;++d){var f=a.charAt(d),g=a.charCodeAt(d);if(55296<=g&&56319>=g&&d+1<e){var k=a.charAt(d+1),l=a.charCodeAt(d+1);56320<=l&&57343>=l&&(f+=k,g=65536+(g-55296<<10)+(l-56320),++d)}if(!(0<=g&&1114109>=g)||55296<=g&&57343>=g||64976<=g&&65007>=g||65534==(g&65534))g=65533,f=String.fromCharCode(g);k=!(32<=g&&126>=g)||" "==f||c&&":"==f||"\\"==f;!c||"/"!=f&&"?"!=f||(c=!1);"%"==f&&(d+2>=e?k=!0:(l=16*(0,window.parseInt)(a.charAt(d+
1),16)+(0,window.parseInt)(a.charAt(d+2),16),0<=l&&255>=l?(g=l,f=0==g?"":"%"+(256+l).toString(16).toUpperCase().substr(1),d+=2):k=!0));k&&(f=(0,window.encodeURIComponent)(f),1>=f.length&&(0<=g&&127>=g?f="%"+(256+g).toString(16).toUpperCase().substr(1):(g=65533,f=(0,window.encodeURIComponent)(String.fromCharCode(g)))));b.push(f)}a=b.join("");a=a.split("#")[0];a=a.split("?");b=a[0].split("/");c=[];d=0;for(e=b.length;d<e;++d)f=b[d],g=f.split("%2E").join("."),g=g.split((0,window.encodeURIComponent)("\uff0e")).join("."),
"."==g?d+1==e&&c.push(""):".."==g?(0<c.length&&c.pop(),d+1==e&&c.push("")):c.push(f);a[0]=c.join("/");for(a=a.join("?");a&&"/"==a.charAt(0);)a=a.substr(1);return"/"+a};_.Hk=function(a){var b=_.Fk(a);if(String(a)!=b)throw Error("G");(a=b)&&"/"==a.charAt(a.length-1)||(a=(a||"")+"/");_.K.register("init",function(){_.Hk(a)});_.Gk=a;_.I.Eb(window.location.href)};
_.Ik="function"==typeof window.atob;
_.Ub.gO=function(a){var b=[];if(1<arguments.length)for(var c=0,d;d=arguments[c];++c)b.push(d);else b=a;return function(a){for(var c=0;b[c];++c)if(a===b[c])return!0;return!1}};_.Ub.OR=function(a){return function(b){return a.test(b)}};_.Ub.iB=function(a){return"undefined"!==typeof a};_.Ub.yQ=function(a){return"string"===typeof a&&0<a.length};_.Ub.wM=function(a){return"boolean"===typeof a};_.Ub.BP=function(a){return function(b){for(var c in a)if(a.hasOwnProperty(c)&&!(0,a[c])(b[c]))return!1;return!0}};

_.I=_.I||{};(function(){function a(a){b=a["core.util"]||{}}var b={},c={};_.Ub&&_.Ub.register("core.util",null,a);_.I.yU=function(a){return"undefined"===typeof b[a]?null:b[a]};_.I.hasFeature=function(a){return"undefined"!==typeof b[a]};_.I.GU=function(){return c}})();

var yg,Ag,Bg,Cg,Dg,Eg,Fg,Gg;yg={};_.zg=function(){this.G="";this.I=yg};_.zg.prototype.Vg=!0;_.zg.prototype.Yd=_.q(2);_.zg.prototype.Gq=!0;_.zg.prototype.wf=_.q(5);Ag=/&/g;Bg=/</g;Cg=/>/g;Dg=/"/g;Eg=/'/g;Fg=/\x00/g;Gg=/[\x00&<>"']/;
_.Hg=function(a){if(!Gg.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Ag,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Bg,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Cg,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Dg,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Eg,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Fg,"&#0;"));return a};_.Ig=function(a){return a instanceof _.jf&&a.constructor===_.jf&&a.J===_.hf?a.G:"type_error:SafeHtml"}; _.Jg=function(a){return a instanceof _.zg&&a.constructor===_.zg&&a.I===yg?a.G:"type_error:SafeUrl"};

_.jf.prototype.wf=_.M(6,function(){return this.I});_.zg.prototype.wf=_.M(5,function(){return 1});var Kg,Lg;Kg=!_.N||9<=_.be;Lg=!_.Nd&&!_.N||_.N&&9<=_.be||_.Nd&&_.$d("1.9.1");_.Mg=_.N&&!_.$d("9");_.Ng=_.N||_.Ld||_.Od;_.Og=_.N&&!(9<=_.be);var Sg,Ug,Wg;_.Qg=function(a,b){var c=b||window.document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):_.Pg(window.document,"*",a,b)};_.Rg=function(a,b){var c=b||window.document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=_.Pg(window.document,"*",a,b)[0];return d||null};
_.Pg=function(a,b,c,d){a=d||a;b=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,g;g=a[f];f++)b==g.nodeName&&(d[e++]=g);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;g=a[f];f++)b=g.className,"function"==typeof b.split&&_.nd(b.split(/\s+/),c)&&(d[e++]=g);d.length=e;return d}return a};
_.Tg=function(a,b){_.Hd(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Sg.hasOwnProperty(d)?a.setAttribute(Sg[d],b):_.$c(d,"aria-")||_.$c(d,"data-")?a.setAttribute(d,b):a[d]=b})};Sg={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
_.Vg=function(a,b){var c=b[0],d=b[1];if(!Kg&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',_.Hg(d.name),'"');if(d.type){c.push(' type="',_.Hg(d.type),'"');var e={};_.Gd(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(_.ka(d)?c.className=d:_.ja(d)?c.className=d.join(" "):_.Tg(c,d));2<b.length&&Ug(a,c,b,2);return c};
Ug=function(a,b,c,d){function e(c){c&&b.appendChild(_.ka(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var f=c[d];!_.Uc(f)||_.Xc(f)&&0<f.nodeType?e(f):(0,_.id)(Wg(f)?_.Id(f):f,e)}};_.Yg=function(a,b){Ug(_.Xg(a),a,arguments,1)};_.Zg=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.$g=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};_.ah=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};
_.bh=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return _.ah(a)}};_.ch=function(a){return Lg&&void 0!=a.children?a.children:(0,_.jd)(a.childNodes,function(a){return 1==a.nodeType})};_.dh=function(a){if(_.ea(a.firstElementChild))a=a.firstElementChild;else for(a=a.firstChild;a&&1!=a.nodeType;)a=a.nextSibling;return a};_.eh=function(a){return _.Xc(a)&&1==a.nodeType};
_.fh=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};_.Xg=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};
_.gh=function(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=b;else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=b}else _.Zg(a),a.appendChild(_.Xg(a).createTextNode(String(b)))};Wg=function(a){if(a&&"number"==typeof a.length){if(_.Xc(a))return"function"==typeof a.item||"string"==typeof a.item;if(_.Yc(a))return"function"==typeof a.item}return!1};_.hh=function(a){this.G=a||_.r.document||window.document};
_.h=_.hh.prototype;_.h.P=_.q(0);_.h.$=function(a,b,c){return _.Vg(this.G,arguments)};_.h.createElement=function(a){return this.G.createElement(a)};_.h.Ra=function(){var a=this.G;return a.parentWindow||a.defaultView};_.h.appendChild=function(a,b){a.appendChild(b)};_.h.append=_.Yg;_.h.jw=_.Zg;_.h.ox=_.$g;_.h.removeNode=_.ah;_.h.kF=_.bh;_.h.AF=_.ch;_.h.Hv=_.dh;_.h.isElement=_.eh;_.h.contains=_.fh;

var $r,as,es,ns,ps;_.Zr=function(a){return"CSS1Compat"==a.compatMode};$r={IMG:" ",BR:"\n"};as={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1};_.bs=function(a){return a.scrollingElement?a.scrollingElement:!_.Od&&_.Zr(a)?a.documentElement:a.body||a.documentElement};_.cs=function(a,b){this.width=a;this.height=b};_.h=_.cs.prototype;_.h.clone=function(){return new _.cs(this.width,this.height)};_.h.isEmpty=function(){return!(this.width*this.height)};_.h.ceil=_.q(9);
_.h.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};_.h.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};_.ds=function(a,b){this.x=_.ea(a)?a:0;this.y=_.ea(b)?b:0};_.h=_.ds.prototype;_.h.clone=function(){return new _.ds(this.x,this.y)};_.h.ceil=_.q(10);_.h.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};
_.h.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};_.h.translate=_.q(13);es=function(a,b,c){if(!(a.nodeName in as))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in $r)b.push($r[a.nodeName]);else for(a=a.firstChild;a;)es(a,b,c),a=a.nextSibling};
_.fs=function(a){var b=_.bs(a);a=a.parentWindow||a.defaultView;return _.N&&_.$d("10")&&a.pageYOffset!=b.scrollTop?new _.ds(b.scrollLeft,b.scrollTop):new _.ds(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};_.gs=function(a){a=a.document;a=_.Zr(a)?a.documentElement:a.body;return new _.cs(a.clientWidth,a.clientHeight)};_.hs=function(a){if(a instanceof _.jf)return a;var b=null;a.Gq&&(b=a.wf());a=_.Hg(a.Vg?a.Yd():String(a));return _.kf(a,b)};
_.ds.prototype.ceil=_.M(10,function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this});_.cs.prototype.ceil=_.M(9,function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this});_.ef.prototype.Yd=_.M(4,function(){return this.G});_.jf.prototype.Yd=_.M(3,function(){return this.G});_.zg.prototype.Yd=_.M(2,function(){return this.G});_.hh.prototype.P=_.M(0,function(a){return _.ka(a)?this.G.getElementById(a):a});_.is=function(a){return _.fs(a.G)};_.js=function(a){return _.Zr(a.G)};
_.ks=function(a,b,c,d){return _.Pg(a.G,b,c,d)};_.ls=function(a){if(_.Mg&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];es(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");_.Mg||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a};_.ms=function(a){return _.gs(a||window)};ns=/^(?:(?:https?|mailto|ftp):|[^&:/?#]*(?:[/?#]|$))/i;_.os=function(a){return a instanceof _.ef&&a.constructor===_.ef&&a.I===_.df?a.G:"type_error:SafeStyle"};
_.qs=function(a){if(a instanceof _.zg)return a;a=a.Vg?a.Yd():String(a);ns.test(a)||(a="about:invalid#zClosurez");var b=new _.zg;b.G=a;return b};_.rs=function(a){return a?new _.hh(_.Xg(a)):ps||(ps=new _.hh)};_.ss=function(a,b,c,d){return _.fd.splice.apply(a,_.Cd(arguments,1))};_.ts=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};_.us=function(a){var b=[];es(a,b,!1);return b.join("")};
_.vs=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};_.ws=function(a,b,c){return _.Vg(window.document,arguments)};_.xs=function(a){return a?a.parentWindow||a.defaultView:window};_.ys=function(a){return _.ka(a)?window.document.getElementById(a):a};_.zs=function(a){var b=_.fa(a);if("object"==b||"array"==b){if(a.clone)return a.clone();var b="array"==b?[]:{},c;for(c in a)b[c]=_.zs(a[c]);return b}return a};_.As=function(a,b,c){if(b in a)throw Error("i`"+b);a[b]=c};
_.Bs=function(a){var b=_.ka(void 0)?_.ts(void 0):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};_.Cs=function(a,b){for(var c in b)a[c]=b[c]};_.Ds=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};_.h=_.Ds.prototype;_.h.Tb=_.q(14);_.h.Qb=function(){return this.bottom-this.top};_.h.clone=function(){return new _.Ds(this.top,this.right,this.bottom,this.left)};
_.h.contains=function(a){return this&&a?a instanceof _.Ds?a.left>=this.left&&a.right<=this.right&&a.top>=this.top&&a.bottom<=this.bottom:a.x>=this.left&&a.x<=this.right&&a.y>=this.top&&a.y<=this.bottom:!1};_.h.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
_.h.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};_.h.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};_.h.translate=_.q(12);
var Fs,Js,Qs,Ys,Zs;_.Q=function(a,b,c){if(_.ka(b))(b=_.Es(a,b))&&(a.style[b]=c);else for(var d in b){c=a;var e=b[d],f=_.Es(c,d);f&&(c.style[f]=e)}};Fs={};_.Es=function(a,b){var c=Fs[b];if(!c){var d=_.dd(b),c=d;void 0===a.style[d]&&(d=(_.Od?"Webkit":_.Nd?"Moz":_.N?"ms":_.Ld?"O":null)+_.Bs(d),void 0!==a.style[d]&&(c=d));Fs[b]=c}return c};_.Gs=function(a,b){var c=_.Xg(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))?c[b]||c.getPropertyValue(b)||"":""};
_.Hs=function(a,b){return a.currentStyle?a.currentStyle[b]:null};_.Is=function(a,b){return _.Gs(a,b)||_.Hs(a,b)||a.style&&a.style[b]};Js=function(a){var b;try{b=a.getBoundingClientRect()}catch(c){return{left:0,top:0,right:0,bottom:0}}_.N&&a.ownerDocument.body&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b};
_.Ks=function(a){var b=_.Xg(a),c=new _.ds(0,0),d;d=b?_.Xg(b):window.document;d=!_.N||9<=_.be||_.js(_.rs(d))?d.documentElement:d.body;if(a==d)return c;a=Js(a);b=_.is(_.rs(b));c.x=a.left+b.x;c.y=a.top+b.y;return c};_.Ms=function(a,b){var c=new _.ds(0,0),d=_.xs(_.Xg(a)),e=a;do{var f=d==b?_.Ks(e):_.Ls(e);c.x+=f.x;c.y+=f.y}while(d&&d!=b&&d!=d.parent&&(e=d.frameElement)&&(d=d.parent));return c};_.Ls=function(a){a=Js(a);return new _.ds(a.left,a.top)};
_.Ps=function(a,b,c){if(b instanceof _.cs)c=b.height,b=b.width;else if(void 0==c)throw Error("L");a.style.width=_.Ns(b,!0);_.Os(a,c)};_.Ns=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};_.Os=function(a,b){a.style.height=_.Ns(b,!0)};_.Rs=function(a){var b=Qs;if("none"!=_.Is(a,"display"))return b(a);var c=a.style,d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";a=b(a);c.display=d;c.position=f;c.visibility=e;return a};
Qs=function(a){var b=a.offsetWidth,c=a.offsetHeight,d=_.Od&&!b&&!c;return _.ea(b)&&!d||!a.getBoundingClientRect?new _.cs(b,c):(a=Js(a),new _.cs(a.right-a.left,a.bottom-a.top))};_.Ss=function(a,b){a.style.display=b?"":"none"};_.Us=function(a){var b=_.rs(void 0),c=null,d=b.G;_.N&&d.createStyleSheet?(c=d.createStyleSheet(),_.Ts(c,a)):(d=_.ks(b,"HEAD")[0],d||(c=_.ks(b,"BODY")[0],d=b.$("HEAD"),c.parentNode.insertBefore(d,c)),c=b.$("STYLE"),_.Ts(c,a),b.appendChild(d,c));return c};
_.Ts=function(a,b){_.N&&_.ea(a.cssText)?a.cssText=b:a.innerHTML=b};_.Vs=function(a){return"rtl"==_.Is(a,"direction")};_.Ws=_.Nd?"MozUserSelect":_.Od?"WebkitUserSelect":null;_.Xs=function(a,b){if(/^\d+px?$/.test(b))return(0,window.parseInt)(b,10);var c=a.style.left,d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b;var e=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=d;return e};Ys={thin:2,medium:4,thick:6};
Zs=function(a,b){if("none"==_.Hs(a,b+"Style"))return 0;var c=_.Hs(a,b+"Width");return c in Ys?Ys[c]:_.Xs(a,c)};_.$s=function(a){if(_.N&&!(9<=_.be)){var b=Zs(a,"borderLeft"),c=Zs(a,"borderRight"),d=Zs(a,"borderTop");a=Zs(a,"borderBottom");return new _.Ds(d,c,a,b)}b=_.Gs(a,"borderLeftWidth");c=_.Gs(a,"borderRightWidth");d=_.Gs(a,"borderTopWidth");a=_.Gs(a,"borderBottomWidth");return new _.Ds((0,window.parseFloat)(d),(0,window.parseFloat)(c),(0,window.parseFloat)(a),(0,window.parseFloat)(b))};

var qv,rv,sv;_.ov=function(a){for(var b=[],c=0,d=0;c<a.length;){var e=a[c++];if(128>e)b[d++]=String.fromCharCode(e);else if(191<e&&224>e){var f=a[c++];b[d++]=String.fromCharCode((e&31)<<6|f&63)}else{var f=a[c++],g=a[c++];b[d++]=String.fromCharCode((e&15)<<12|(f&63)<<6|g&63)}}return b.join("")};_.pv=null;qv=null;rv=null;sv=null;_.tv=_.Nd||_.Od||_.Ld||"function"==typeof _.r.atob;
_.vv=function(a,b){var c;if(_.tv&&!b)c=_.r.atob(a);else if(c=_.uv(a,b),8192>=c.length)c=String.fromCharCode.apply(null,c);else{for(var d="",e=0;e<c.length;e+=8192)d+=String.fromCharCode.apply(null,_.Cd(c,e,e+8192));c=d}return c};
_.uv=function(a,b){_.wv();for(var c=b?sv:qv,d=[],e=0;e<a.length;){var f=c[a.charAt(e++)],g=e<a.length?c[a.charAt(e)]:0;++e;var k=e<a.length?c[a.charAt(e)]:64;++e;var l=e<a.length?c[a.charAt(e)]:64;++e;if(null==f||null==g||null==k||null==l)throw Error();d.push(f<<2|g>>4);64!=k&&(d.push(g<<4&240|k>>2),64!=l&&d.push(k<<6&192|l))}return d};
_.wv=function(){if(!_.pv){_.pv={};qv={};rv={};sv={};for(var a=0;65>a;a++)_.pv[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a),qv[_.pv[a]]=a,rv[a]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charAt(a),sv[rv[a]]=a,62<=a&&(qv["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charAt(a)]=a,sv["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(a)]=a)}};

_.xv=function(a){this.G=a};_.xv.prototype.toString=function(){return this.G};_.yv=function(){_.pe.call(this);this.M=1;this.J=[];this.K=0;this.G=[];this.I={}};_.u(_.yv,_.pe);_.h=_.yv.prototype;_.h.subscribe=_.q(34);_.h.Gf=function(a){if(0!=this.K)return this.J.push(a),!1;var b=this.G[a];if(b){var c=this.I[b];c&&_.oe(c,a);delete this.G[a];delete this.G[a+1];delete this.G[a+2]}return!!b};
_.h.jm=function(a,b){var c=this.I[a];if(c){this.K++;for(var d=Array(arguments.length-1),e=1,f=arguments.length;e<f;e++)d[e-1]=arguments[e];e=0;for(f=c.length;e<f;e++){var g=c[e];this.G[g+1].apply(this.G[g+2],d)}this.K--;if(0<this.J.length&&0==this.K)for(;c=this.J.pop();)this.Gf(c);return 0!=e}return!1};_.h.clear=function(a){if(a){var b=this.I[a];b&&((0,_.id)(b,this.Gf,this),delete this.I[a])}else this.G.length=0,this.I={}}; _.h.ob=function(a){if(a){var b=this.I[a];return b?b.length:0}a=0;for(b in this.I)a+=this.ob(b);return a};_.h.ja=function(){_.yv.R.ja.call(this);this.clear();this.J.length=0};
_.zv=function(){_.pe.call(this);this.G=new _.yv;_.re(this,this.G)};_.u(_.zv,_.pe);_.zv.prototype.subscribe=_.q(33);_.zv.prototype.Gf=function(a){return this.G.Gf(a)};_.zv.prototype.clear=function(a){this.G.clear(_.ea(a)?a.toString():void 0)};_.zv.prototype.ob=function(a){return this.G.ob(_.ea(a)?a.toString():void 0)};

var Av={},Bv=function(){this.G=Av},Cv,Dv,Ev,Gv,Iv,Jv,Kv,Lv;Bv.prototype.Vg=!0;Bv.prototype.Yd=function(){return""};Bv.prototype.toString=function(){return"Const{}"};Cv={};Dv=/^[-,."'%_!# a-zA-Z0-9]+$/;Ev=function(a){return a instanceof Bv&&a.constructor===Bv&&a.G===Av?"":"type_error:Const"};_.Fv=function(){this.G=Cv};_.Fv.prototype.Vg=!0;_.Fv.prototype.Yd=function(){return""};_.Fv.prototype.Gq=!0;_.Fv.prototype.wf=function(){return 1};
Gv={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0};_.Hv=function(a){return a instanceof _.Fv&&a.constructor===_.Fv&&a.G===Cv?"":"type_error:TrustedResourceUrl"};Iv=function(a){var b=0,c="",d=function(a){_.ja(a)?(0,_.id)(a,d):(a=_.hs(a),c+=_.Ig(a),a=a.wf(),0==b?b=a:0!=a&&b!=a&&(b=null))};(0,_.id)(arguments,d);return _.kf(c,b)};Jv=/^[a-zA-Z0-9-]+$/;Kv={EMBED:!0,IFRAME:!0,LINK:!0,OBJECT:!0,SCRIPT:!0,STYLE:!0,TEMPLATE:!0};Lv=function(a,b){return a>b?1:a<b?-1:0};
_.Mv=function(a,b){a.sort(b||Lv)};_.Nv=function(a,b){_.ja(b)||(b=[b]);var c=(0,_.kd)(b,function(a){return _.ka(a)?a:a.hn+" "+a.duration+"s "+a.timing+" "+a.Dg+"s"});_.Q(a,"transition",c.join(","))};
_.Ov=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){if(_.N)return _.$d("10.0");var a=window.document.createElement("DIV"),b=_.Od?"-webkit":_.Nd?"-moz":_.N?"-ms":_.Ld?"-o":null,c={transition:"opacity 1s linear"};b&&(c[b+"-transition"]="opacity 1s linear");b={style:c};if(!Jv.test("div"))throw Error("n`div");if("DIV"in Kv)throw Error("o`div");var c=null,d="<div";if(b)for(var e in b){if(!Jv.test(e))throw Error("s`"+e);var f=b[e];if(null!=f){var g;g=e;if(f instanceof Bv)f=
Ev(f);else if("style"==g.toLowerCase()){if(!_.Xc(f))throw Error("r`"+typeof f+"`"+f);if(!(f instanceof _.ef)){var k="",l=void 0;for(l in f){if(!/^[-_a-zA-Z0-9]+$/.test(l))throw Error("m`"+l);var m=f[l];if(null!=m){if(m instanceof Bv)m=Ev(m);else if(Dv.test(m)){for(var n=!0,p=!0,v=0;v<m.length;v++){var z=m.charAt(v);"'"==z&&p?n=!n:'"'==z&&n&&(p=!p)}n&&p||(m="zClosurez")}else m="zClosurez";k+=l+":"+m+";"}}f=k?_.ff(k):_.gf}f=_.os(f)}else{if(/^on/i.test(g))throw Error("p`"+g+"`"+f);if(g.toLowerCase()in
Gv)if(f instanceof _.Fv)f=_.Hv(f);else if(f instanceof _.zg)f=_.Jg(f);else if(_.ka(f))f=_.qs(f).Yd();else throw Error("q`"+g+"`div`"+f);}f.Vg&&(f=f.Yd());g=g+'="'+_.Hg(String(f))+'"';d=d+(" "+g)}}e=void 0;null!=e?_.ja(e)||(e=[e]):e=[];!0===_.cf.div?d+=">":(c=Iv(e),d+=">"+_.Ig(c)+"</div>",c=c.wf());(b=b&&b.dir)&&(/^(ltr|rtl|auto)$/i.test(b)?c=0:c=null);b=_.kf(d,c);a.innerHTML=_.Ig(b);a=a.firstChild;b=a.style[_.dd("transition")];return""!=("undefined"!==typeof b?b:a.style[_.Es(a,"transition")]||"")});

_.Rv=function(){_.Qv="oauth2relay"+String(2147483647*(0,_.jk)()|0);_.Pv.proxy=_.Qv};_.Sv=new _.zv;_.Tv=new _.xv("oauth");_.Pv={};_.Rv();var Uv=_.E("oauth-flow/client_id");_.Pv.client_id=Uv;var Vv=_.Pv,Wv;var Xv=String(_.E("oauth-flow/redirectUri"));if(Xv)Wv=Xv.replace(/[#][\s\S]*/,"");else{var Yv=_.ej.Ja(window.location.href);Wv=[_.E("oauth-flow/callbackUrl"),"?x_origin=",(0,window.encodeURIComponent)(Yv)].join("")}Vv.redirect_uri=Wv;_.Pv.origin=_.ej.Ja(window.location.href);_.Pv.response_type="token";

var aw,$v,bw,cw,dw,ew,fw,gw,hw,iw,jw,kw,lw,mw,nw,ow,pw,qw,rw,tw,uw,vw,ww,xw,yw,Aw,Bw,Cw,Dw,Ew,Fw,Gw,Hw,Iw,Jw,Kw,Lw,Mw,Nw,Pw,Qw,Rw,Sw,Tw,Uw,Vw,Ww,Xw,Yw,Zw,bx,cx,ex;_.yv.prototype.subscribe=_.M(34,function(a,b,c){var d=this.I[a];d||(d=this.I[a]=[]);var e=this.M;this.G[e]=a;this.G[e+1]=b;this.G[e+2]=c;this.M=e+3;d.push(e);return e});_.zv.prototype.subscribe=_.M(33,function(a,b,c){return this.G.subscribe(a.toString(),b,c)});
_.Zv=function(a,b,c,d){if(b=a.I[b]){var e=a.G;(b=_.he(b,function(a){return e[a+1]==c&&e[a+2]==d}))&&a.Gf(b)}};aw=function(a){var b=$v;_.Nv(b,[{hn:"-webkit-transform",duration:1,timing:"ease",Dg:0}]);_.Nv(b,[{hn:"transform",duration:1,timing:"ease",Dg:0}]);_.th(function(){b.style.webkitTransform="translate3d(0px,"+a+"px,0px)";b.style.transform="translate3d(0px,"+a+"px,0px)"},0)};
cw=function(a){var b=_.Rj(a);if(!b)return new _.xj("G_USERSTATE_");a=["G_USERSTATE_",_.Dj&&b.Fb?"S":"H",b.Cd].join("");var c=_.Mj[a];c||(c={eV:63072E3},_.Oa(_.Tj(b),c),c=new _.uj(a,c),_.Mj[a]=c,b=c.read(),"undefined"!==typeof b&&null!==b&&(window.document.cookie=a+"=; expires=Thu, 01 Jan 1970 00:00:01 GMT; path=/",c.write(b)));return c};dw=function(a){a=a&&a.id_token;if(!a||!a.split(".")[1])return null;a=(a.split(".")[1]+"...").replace(/^((....)+).?.?.?$/,"$1");return _.jh(_.vv(a,!0))};ew=function(){$v.parentNode.removeChild($v)};
fw=function(){var a=bw+88;aw(a);bw=a};gw=function(){var a=bw-88;aw(a);bw=a};hw=function(a){var b=cw(a).read();a=_.Ka();if(b)for(var b=b.split(":"),c;c=b.shift();)c=c.split("="),a[c[0]]=c[1];return a};iw=function(a){if(!a)return[];a=a.split("=");return a[1]?a[1].split("|"):[]};jw=function(a){return(a=dw(a))?a.sub:null};
kw=function(a){var b=a?fw:gw,c=a?gw:fw;a=a?"-":"";bw=(0,window.parseInt)(a+88,10);$v.style.webkitTransform="translate3d(0px,"+a+88+"px,0px)";$v.style.transform="translate3d(0px,"+a+88+"px,0px)";$v.style.display="";$v.style.visibility="visible";b();_.th(c,4E3);_.th(ew,5E3)};lw=function(){var a,b=null;_.Ej.iterate(function(c,d){if(0===c.indexOf("G_AUTHUSER_")){var e=_.Fj(c.substring(11));if(!a||e.Fb&&!a.Fb||e.Fb==a.Fb&&e.Cd>a.Cd)a=e,b=d}});return{$D:a,Dh:b}};
mw=function(a){a=a.split(":");return{Gu:a[0].split("=")[1],EK:iw(a[1]),cV:iw(a[2]),vU:iw(a[3])}};nw=function(a){a=_.Rj(a);if(!a||a.Fb&&!_.Dj)return null;var b=["G_AUTHUSER_",_.Dj&&a.Fb?"S":"H",a.Cd].join(""),c=_.Lj[b];c||(c=new _.Ej(b,_.Tj(a)),_.Lj[b]=c);return c};ow=function(a){var b=jw(a);b?(a=hw(a.cookie_policy),b="0"==a[b]||"X"==a[b]):b=!1;return b};
pw=function(a){var b=_.E("oauth-flow/toast/position");"top"!==b&&(b="bottom");var c=window.document.createElement("div");$v=c;c.style.cssText="position:fixed;left:0px;z-index:1000;width:100%;";var d;_.Q(c,"visibility","hidden");_.Q(c,b,"-40px");_.Q(c,"height","128px");d=c;if("desktop"==_.E("deviceType")){d=window.document.createElement("div");d.style.cssText="float:left;position:relative;left:50%;";c.appendChild(d);var e=window.document.createElement("div");e.style.cssText="float:left;position:relative;left:-50%";
d.appendChild(e);d=e}e="top"==b?"-":"";bw=(0,window.parseInt)(e+88,10);$v.style.webkitTransform="translate3d(0px,"+e+88+"px,0px)";$v.style.transform="translate3d(0px,"+e+88+"px,0px)";e=window;try{for(;e.parent!=e&&e.parent.document;)e=e.parent}catch(f){}e=e.document.body;try{e.insertBefore(c,e.firstChild)}catch(g){}_.Um.$e({url:":socialhost:/:session_prefix:_/widget/oauthflow/toast",queryParams:{clientId:a.client_id,idToken:a.id_token},where:d,onRestyle:function(){"top"===b?kw(!0):kw(!1)}})};qw=!1;
rw=!1;_.sw=function(a){_.Db(a)&&_.Ib(a)};uw=function(a){var b=lw(),c=b.$D,b=b.Dh,d=a&&_.Hj(a);if(null!==b){var e;_.Ej.iterate(function(a,b){var f=_.Ij(a);f&&f.Kc&&(d&&f.Hu!=d||f.Fb==c.Fb&&f.Cd==c.Cd&&(e=b))});if(e){var f=mw(e);a=f&&f.EK[Number(b)];f=f&&f.Gu;if(a)return{Dh:b,JV:a,Gu:f}}}return null};vw=function(a){a=nw(a.g_user_cookie_policy);_.hb("googleapis.config/sessionIndex",null);a.clear()};ww=function(a){return"true"===String(a.immediate)};
xw=function(a,b){var c=null;if(a&&b){c=b.client_id=b.client_id||a.client_id;b.scope=b.scope||a.scope;b.g_user_cookie_policy=a.cookie_policy;b.cookie_policy=b.cookie_policy||a.cookie_policy;b.response_type=b.response_type||a.response_type;var d=_.E("iframes/signin/iframeType");!qw&&b.error&&ww(a)&&(_.sw("gapi.signin.impression."+d+"."+c),qw=!0)}b&&(b.issued_at||(b.issued_at=String(_.tj())),d=(0,window.parseInt)(b.expires_in,10)||86400,b.error&&(d=_.E("oauth-flow/errorMaxAge")||86400),b.expires_in=
String(d),b.expires_at||(b.expires_at=String(_.tj()+d)),a&&ww(a)||(b["g-oauth-window"]=(tw||{}).popup),b._aa||b.error||null!=uw(c)||!ww(a)||(b._aa="1"),c=b.status={},c.google_logged_in=!!b.session_state,d=c.signed_in=!!b.access_token,c.method=d?b["g-oauth-window"]?"PROMPT":"AUTO":null);return b};yw={};
_.zw=function(a,b){var c,d;"string"==typeof a?(c=b,d=a):(c=a,d="token");if(c){var e=_.Vj(c,!0);if(e){var f;if((f=c)&&f.session_state){var g=[],k=[],l=[],m=(0,window.parseInt)(f.authuser,10)||0;g[m]=f.session_state;k[m]=f.issued_at;l[m]=f.expires_at;f=["C="+f.client_id,"S="+g.join("|"),"I="+k.join("|"),"X="+l.join("|")].join(":")}else f=null;f&&e.fe.write(f);"token"==d&&(e=nw(c.g_user_cookie_policy))&&(c.error?vw(c):c.session_state&&e.write(c.authuser||"0"))}}if(d="token"!==d?_.Uj(d):_.Vj(c))if(c){if(d.fe.write(c),
!_.Nj||d.uF&&"token"!==_.Nj)_.Nj=d.key}else d.fe.clear(),_.Nj=null;_.Wj(void 0,void 0)};Aw=function(a,b){var c=b&&b.key||"token",d=a=xw(b&&b.params,a);!ow(d)&&0<=(" "+(d.scope||"")+" ").indexOf(" https://www.googleapis.com/auth/plus.login ")&&_.E("isLoggedIn")&&"1"===d._aa&&(d._aa="0",rw||(rw=!0,pw(d)));_.zw(c,a);a=_.Wj(c,void 0);if(b){c=b.popup;d=b.after_redirect;if(c&&"keep_open"!=d)try{c.close()}catch(e){}b.callback&&(b.callback(a),b.callback=null)}};Bw={};Cw=function(){return!!_.E("oauth-flow/usegapi")};
Dw=function(a){var b=_.Qv;return function(c){if(this.f==b&&this.t==_.K.Gg(this.f)&&this.origin==_.K.Sf(this.f))return a.apply(this,arguments)}};Ew=null;Fw=[];Gw=function(a,b,c){Cw()?Ew.register(a,c,_.en):_.K.register(a+":"+b,Dw(c))};Hw={};Iw=0;
Jw=function(a){a&&Fw.push(a);a=_.Qv;var b=window.document.getElementById(a),c=(new Date).getTime();if(b){if(Iw&&6E4>c-Iw)return;b.parentNode.removeChild(b);if(/Firefox/.test(window.navigator.userAgent))try{window.frames[a]=void 0}catch(d){}_.Rv();a=_.Qv}Iw=c;var e=String(2147483647*(0,_.jk)()|0),b=_.E("oauth-flow/proxyUrl")||_.E("oauth-flow/relayUrl");if(Cw())Ew=_.Um.$e({where:_.I.Ul(),url:b,id:a,attributes:{style:{width:"1px",height:"1px",position:"absolute",top:"-100px"}},dontclear:!0});else{var b=
[b,"?parent=",(0,window.encodeURIComponent)(_.ej.Ja(window.location.href)),"#rpctoken=",e,"&forcesecure=1"].join(""),c=_.I.Ul(),f=_.I.To({name:a,id:a});f.src=b;f.style.width="1px";f.style.height="1px";f.style.position="absolute";f.style.top="-100px";f.tabIndex="-1";c.appendChild(f);_.K.zk(a)}Gw("oauth2relayReady",e,function(){Cw()?Ew.unregister("oauth2relayReady"):_.K.unregister("oauth2relayReady:"+e);var a=Fw;if(null!==a){Fw=null;for(var b=0,c=a.length;b<c;b++)a[b]()}});Gw("oauth2callback",e,function(a){var b=
_.I.Eb;a=b(a);var b=a.state,c;c=b.replace(/\|.*$/,"");a.state={}.hasOwnProperty.call(yw,c)?yw[c]:null;null!=a.state&&(c=Bw[b],delete Bw[b],Aw(a,c))})};Kw=function(a){var b={error:"user_signed_out"};b.client_id=a.client_id;b.g_user_cookie_policy=a.g_user_cookie_policy;b.scope=a.scope;b.response_type=a.response_type;b.session_state=a.session_state;return xw(null,b)};
Lw=function(a,b){var c=a||{},d;for(d in _.Pv)_.ea(c[d])||(c[d]=_.Pv[d]);a=c;c=_.E("googleapis/overrideClientId");null!=c&&(a.client_id=c);if(!a.redirect_uri||"postmessage"===a.redirect_uri){c=a;d=a.state||"";d=String(d);var e="";if({}.hasOwnProperty.call(Hw,d))e=Hw[d];else{for(var f=2147483647*(0,_.jk)()|0;;){e=String(f);if(!{}.hasOwnProperty.call(yw,e))break;f+=(0,_.jk)()}yw[e]=d;Hw[d]=e}c.state=e+"|"+(0,_.jk)();Bw[a.state]=b}c=a.authorize_uri||_.E("oauth-flow/authUrl");delete a.authorize_uri;c+=
0<c.indexOf("?")?"&":"?";c+=_.Qj(a);c=_.oj(c);d=_.E("iframes/signin/iframeType");"blue"==d?c+="&e=3100070":"red"==d?c+="&e=3100071":"default"==d&&(c+="&e=3100077");return c};Mw=function(a){var b=_.lo(),c=b&&b.scope,b=a&&a.scope,b="string"===typeof b?b.split(" "):b||[];if(c){for(var c=c.split(" "),d=0;d<c.length;++d){var e=c[d];-1==_.Ob.call(b,e)&&b.push(e)}0<b.length&&(a.scope=b.join(" "))}return a};
Nw=function(a){if(!_.ea(a.include_granted_scopes)){var b=_.E("include_granted_scopes"),c=_.lo().include_granted_scopes;_.ea(b)?a.include_granted_scopes=!!b:_.ea(c)&&(a.include_granted_scopes="1"==c||"true"==c)}return a};_.Ow=function(a){null===Fw?a&&a():Jw(a)};Pw=function(a,b,c,d){var e=hw(c),f=e[a];e[a]=b?"0":"1";var g=[];_.mb(e,function(a,b){g.push(b+"="+a)});b=g.join(":");c=cw(c);b?c.write(b):c.clear();e[a]!==f&&d&&d()};
Qw=function(a,b){for(var c=a.split(" "),d=b.split(" "),e=_.Ka(),f=0,g=d.length;f<g;++f)d[f]&&(e[d[f]]=1);f=0;for(g=c.length;f<g;++f)if(c[f]&&!e[c[f]])return!1;return!0};Rw=function(a){if(!a)return null;var b,c,d=_.Hj(a);_.Bj.iterate(function(a){var f=_.Ij(a);f&&f.Kc&&f.Hu===d&&(!b||f.Fb&&!b.Fb||f.Fb==b.Fb&&f.Cd>b.Cd)&&(b=f,c=a)});return c};
Sw=function(a){if(Cw()){var b=_.Um.$e({where:_.I.Ul(),url:a.uri,attributes:{style:{width:"1px",height:"1px",position:"absolute",top:"-100px"}},dontclear:!0});window.setTimeout(function(){b.close()},3E5)}else{var c=_.I.Ul(),b=_.I.To();b.src=a.uri;b.style.width="1px";b.style.height="1px";b.style.position="absolute";b.style.top="-100px";window.setTimeout(function(){b.parentNode&&b.parentNode.removeChild(b)},3E5);c.appendChild(b)}};
Tw=function(a,b){if(tw){var c=tw.popup,d=tw.after_redirect;if(c&&"keep_open"!=d&&!ww(a))try{c.close()}catch(e){}}c=tw={};"key"in a&&(c.key=a.key,delete a.key);a=Nw(a);c.params=Mw(a);c.callback=function(c){ww(a)||!c||c.error||Pw(jw(c),!1,c.cookie_policy);ow(c)&&ww(a)&&(c=Kw(c));(b||function(){})(xw(a,c))};c.uri=Lw(a,c);return c};
Uw=function(a,b){_.Ow(function(){Cw()?Ew.send("check_session_state",{session_state:a.session_state,client_id:a.client_id},function(a){b.call(null,a[0])},_.en):_.K.call(_.Qv,"check_session_state",Dw(function(a){b.call(null,a)}),a.session_state,a.client_id)})};Vw=function(a){a=_.I.Eb("#"+_.Qj(a));if(!ww(a))return null;var b=a.key||Rw(a.client_id);return(b=_.Wj(b,!0,!0))&&b.client_id===a.client_id&&Qw(a.scope,b.scope)&&Qw(a.response_type,b.response_type)?b:null};
Ww=function(a,b){var c=_.I.Eb();a.hl=c.lang||c.hl||_.E("lang");var d=Tw(a,b);a.after_redirect&&(d.after_redirect=a.after_redirect);if(null!=a.scope&&null!=a.client_id){var e=function(){_.Ow(function(){if(d.popup)d.popup.focus();else if(ww(a))Sw(d);else{var b=Math.min(_.E("oauth-flow/authWindowWidth",650),window.screen.width-20),c=Math.min(_.E("oauth-flow/authWindowHeight",600),window.screen.height-30);tw.popup=window.open(d.uri,"_blank",["toolbar=no","location="+(window.opera?"no":"yes"),"directories=no,status=no,menubar=no,scrollbars=yes,resizable=yes,copyhistory=no",
"width="+b,"height="+c,"top="+(window.screen.height-c)/2,"left="+(window.screen.width-b)/2].join())}})},f=Vw(a);!_.E("oauth-flow/disableOpt")&&f?Uw(f,function(a){a?Aw(f,tw):e()}):e()}else Aw(null,tw),_.Sb("Unable to perform authorization: scope and/or client_idparameters missing.")};
Xw=function(a){a||(a=_.Wj(void 0,!0));a&&"object"===typeof a||(a={error:"invalid_request",error_description:"no callback data"});var b=a.error_description;b&&window.console&&(window.console.error(a.error),window.console.error(b));a.error||(_.$a.drw=null);_.zw(a);if(b=a.authuser)_.E("googleapis.config/sessionIndex"),_.hb("googleapis.config/sessionIndex",b);_.Sv.G.jm(_.Tv.toString(),a);return a};
Yw=function(a,b){var c=a||{},d=b||function(){};if(_.E("oauth-flow/disableOpt")||_.E("isLoggedIn")||!ww(c))Ww(c,d);else{var e=_.Ka();e.client_id=c.client_id;e.session_state=null;Uw(e,function(a){a?(a=_.Ka(),a.error="immediate_failed_user_logged_out",d(xw(c,a))):(_.hb("isLoggedIn",!0),Ww(c,d))})}};Zw=function(a,b){var c=jw(a);c&&(vw(a),Pw(c,!0,b,function(){Xw&&Xw(Kw(a))}))};
_.$w=function(a,b){var c=new _.$f(function(b,c){var f=function(a){null==a||a.error?c(a):b(a)};try{Yw(a,f)}catch(g){c(g)}});b&&c.then(b,function(a){b(Xw(a))});return c};_.ax=function(a){_.Rb&&(_.Rb.error?_.Rb.error(a):_.Rb.log&&_.Rb.log(a))};bx=_.hk.Tl;cx=null;
_.fx=function(a,b){if("force"!==a.approvalprompt){var c=_.dx(a);c.immediate=!0;delete c.redirect_uri;delete c.approval_prompt;var d;if(d=!b)cx?(c.client_id!==cx.client_id&&window.console&&window.console.log&&window.console.log("Ignoring mismatched page-level auth param client_id="+c.client_id),d=!0):(cx=c,d=!1);d||ex(c)}};
_.dx=function(a){var b=a.redirecturi||"postmessage",c=(0,_.ad)((a.scope||"").replace(/[\s\xa0]+/g," ")),b={client_id:a.clientid,redirect_uri:b,response_type:"code token id_token gsession",scope:c};a.approvalprompt&&(b.approval_prompt=a.approvalprompt);a.state&&(b.state=a.state);a.openidrealm&&(b["openid.realm"]=a.openidrealm);c="offline"==a.accesstype?!0:(c=a.redirecturi)&&"postmessage"!=c;c&&(b.access_type="offline");a.requestvisibleactions&&(b.request_visible_actions=(0,_.ad)(a.requestvisibleactions.replace(/[\s\xa0]+/g,
" ")));a.after_redirect&&(b.after_redirect=a.after_redirect);a.cookiepolicy&&"none"!==a.cookiepolicy&&(b.cookie_policy=a.cookiepolicy);"none"===a.cookiepolicy&&_.sw("gapi.signin.cpnone");"undefined"!=typeof a.includegrantedscopes&&(b.include_granted_scopes=a.includegrantedscopes);a.e&&(b.e=a.e);(a=a.authuser||_.E("googleapis.config/sessionIndex"))&&(b.authuser=a);(a=_.E("useoriginassocialhost"))&&(b.use_origin_as_socialhost=a);return b};
ex=function(a){_.fp("waaf0","signin","0");_.$w(a,function(a){_.fp("waaf1","signin","0");Xw(a)})};_.gx=function(a){a=_.dx(a);_.hb("oauth-flow/authWindowWidth",445);_.hb("oauth-flow/authWindowHeight",615);ex(a)};_.hx=function(a){_.Zv(_.Sv.G,_.Tv.toString(),a,void 0);_.Sv.subscribe(_.Tv,a)};
var ox,rx;_.jx=function(a){return a.cookiepolicy?!0:(_.ix("cookiepolicy is a required field.  See https://developers.google.com/+/web/signin/#button_attr_cookiepolicy for more information."),!1)};_.ix=function(a){window.console&&(window.console.error?window.console.error(a):window.console.log&&window.console.log(a))};_.nx=function(a,b){var c=_.lo();_.Oa(a,c);c=Mw(c);if(_.jx(c)){var d=_.kx(c);_.lx(c);b?_.Ya(b,"click",function(){_.mx(c,d)}):_.mx(c,d)}};
_.kx=function(a){var b=new ox;_.hx(function(c){if(b.G&&c&&(c.access_token&&_.hb("isPlusUser",!0),c["g-oauth-window"]))if(b.G=!1,c.access_token&&"consent"==c.prompt){var d=c["g-oauth-window"];c=c.id_token;var e=a.apppackagename;if(e&&d){var f=!0;try{f=d.closed}catch(g){}f||(c=_.E("iframes/:socialhost:")+"/_/history/otaappinstall?clientId="+(0,window.encodeURIComponent)(a.clientid)+"&appId="+(0,window.encodeURIComponent)(e)+"&idToken="+(0,window.encodeURIComponent)(c),c=_.oj(c),d.location.href=c)}}else if(d=
c["g-oauth-window"],a.apppackagename&&d)try{d.close()}catch(k){}});return b};ox=function(){this.G=!1};_.lx=function(a){a=_.px(a);_.qx(a.callback);_.Ow(function(){_.fx(a)})};_.px=function(a){rx(a);a.apppackagename&&(a.after_redirect="keep_open");a.redirecturi&&delete a.redirecturi;_.nj(function(b){return a[b]})||(a.authuser=0);a.apppackagename&&(a.apppackagename=a.apppackagename.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));return a};rx=function(a){/^\s*$/.test(a.scope||"")&&(a.scope="https://www.googleapis.com/auth/plus.login")}; _.qx=function(a){if("string"===typeof a)if(window[a])a=window[a];else{_.ix('Callback function named "'+a+'" not found');return}a&&_.hx(a)};_.mx=function(a,b){b.G=!0;var c;c=_.px(a);_.gx(c)};
_.D("gapi.auth.authorize",_.$w);_.D("gapi.auth.checkSessionState",Uw);_.D("gapi.auth.getAuthHeaderValueForFirstParty",bx);_.D("gapi.auth.getToken",function(a,b){return _.Wj(a,b)});_.D("gapi.auth.getVersionInfo",function(a,b){_.Ow(function(){var c=_.hk.Tl()||"",d=null,e=null;c&&(e=c.split(" "),2==e.length&&(d=e[1]));d?Cw()?Ew.send("get_versioninfo",{xapisidHash:d,sessionIndex:b},function(b){a(b[0])},_.en):_.K.call(_.Qv,"get_versioninfo",Dw(function(b){a(b)}),d,b):a()})});_.D("gapi.auth.init",_.Ow);
_.D("gapi.auth.setToken",_.zw);_.D("gapi.auth.signIn",function(a){_.nx(a)});_.D("gapi.auth.signOut",function(){var a=_.Wj(void 0,void 0);a&&Zw(a,a.cookie_policy)});_.D("gapi.auth.unsafeUnpackIdToken",dw);_.D("gapi.auth._pimf",_.fx);_.D("gapi.auth._oart",pw);_.D("gapi.auth._guss",function(a){return cw(a).read()});
var sx=_.lo();sx.clientid&&sx.scope&&sx.cookiepolicy&&_.sw("gapi.auth.pageLevelConfig("+_.qb(sx).sort().join("-")+")");sx.clientid&&sx.scope&&sx.callback&&!_.E("disableRealtimeCallback")?_.lx(sx):_.Ow();
/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
_.pg=function(a,b){this.O=[];this.W=a;this.ma=b||null;this.K=this.I=!1;this.J=void 0;this.S=this.ha=this.U=!1;this.N=0;this.G=null;this.M=0};_.pg.prototype.cancel=function(a){if(this.I)this.J instanceof _.pg&&this.J.cancel();else{if(this.G){var b=this.G;delete this.G;a?b.cancel(a):(b.M--,0>=b.M&&b.cancel())}this.W?this.W.call(this.ma,this):this.S=!0;this.I||this.Ll(new _.qg)}};_.pg.prototype.T=function(a,b){this.U=!1;rg(this,a,b)};
var rg=function(a,b,c){a.I=!0;a.J=c;a.K=!b;sg(a)},ug=function(a){if(a.I){if(!a.S)throw new tg;a.S=!1}};_.h=_.pg.prototype;_.h.Yb=function(a){ug(this);rg(this,!0,a)};_.h.Ll=function(a){ug(this);rg(this,!1,a)};_.h.Xb=function(a,b){return this.If(a,null,b)};_.h.If=function(a,b,c){this.O.push([a,b,c]);this.I&&sg(this);return this};_.h.then=function(a,b,c){var d,e,f=new _.$f(function(a,b){d=a;e=b});this.If(d,function(a){a instanceof _.qg?f.cancel():e(a)});return f.then(a,b,c)};_.Xf(_.pg);
_.pg.prototype.Y=_.q(8);
var vg=function(a){return(0,_.ld)(a.O,function(a){return _.Yc(a[1])})},sg=function(a){if(a.N&&a.I&&vg(a)){var b=a.N,c=wg[b];c&&(_.r.clearTimeout(c.xa),delete wg[b]);a.N=0}a.G&&(a.G.M--,delete a.G);for(var b=a.J,d=c=!1;a.O.length&&!a.U;){var e=a.O.shift(),f=e[0],g=e[1],e=e[2];if(f=a.K?g:f)try{var k=f.call(e||a.ma,b);_.ea(k)&&(a.K=a.K&&(k==b||k instanceof Error),a.J=b=k);if(_.Yf(b)||"function"===typeof _.r.Promise&&b instanceof _.r.Promise)d=!0,a.U=!0}catch(l){b=l,a.K=!0,vg(a)||(c=!0)}}a.J=b;d&&(k=
(0,_.t)(a.T,a,!0),d=(0,_.t)(a.T,a,!1),b instanceof _.pg?(b.If(k,d),b.ha=!0):b.then(k,d));c&&(b=new xg(b),wg[b.xa]=b,a.N=b.xa)},tg=function(){_.Df.call(this)};_.u(tg,_.Df);tg.prototype.message="Deferred has already fired";tg.prototype.name="AlreadyCalledError";_.qg=function(){_.Df.call(this)};_.u(_.qg,_.Df);_.qg.prototype.message="Deferred was canceled";_.qg.prototype.name="CanceledError";var xg=function(a){this.xa=_.r.setTimeout((0,_.t)(this.I,this),0);this.G=a}; xg.prototype.I=function(){delete wg[this.xa];throw this.G;};var wg={};

_.It=function(a){if(!_.ja(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0};_.Jt=function(a){_.pe.call(this);this.S=a;this.J={}};_.u(_.Jt,_.pe);var Kt=[];_.Jt.prototype.V=function(a,b,c,d){return _.Lt(this,a,b,c,d)};_.Lt=function(a,b,c,d,e,f){_.ja(c)||(c&&(Kt[0]=c.toString()),c=Kt);for(var g=0;g<c.length;g++){var k=_.P(b,c[g],d||a.handleEvent,e||!1,f||a.S||a);if(!k)break;a.J[k.key]=k}return a};
_.Jt.prototype.Qa=function(a,b,c,d,e){if(_.ja(b))for(var f=0;f<b.length;f++)this.Qa(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.S||this,c=_.Oe(c),d=!!d,b=_.Ce(a)?_.Ke(a.Ne,String(b),c,d,e):a?(a=_.Qe(a))?_.Ke(a,b,c,d,e):null:null,b&&(_.We(b),delete this.J[b.key]);return this};_.Mt=function(a){_.Hd(a.J,function(a,c){this.J.hasOwnProperty(c)&&_.We(a)},a);a.J={}};_.Jt.prototype.ja=function(){_.Jt.R.ja.call(this);_.Mt(this)};_.Jt.prototype.handleEvent=function(){throw Error("M");};

var ru,tu,uu,Hu,Cu,Nu,Du,Fu,Eu,Ku,Gu,Ou;ru=/#|$/;_.su=function(a,b){var c=a.search(ru),d;a:{d=0;for(var e=b.length;0<=(d=a.indexOf(b,d))&&d<c;){var f=a.charCodeAt(d-1);if(38==f||63==f)if(f=a.charCodeAt(d+e),!f||61==f||38==f||35==f)break a;d+=e+1}d=-1}if(0>d)return null;e=a.indexOf("&",d);if(0>e||e>c)e=c;d+=b.length+1;return(0,window.decodeURIComponent)(a.substr(d,e-d).replace(/\+/g," "))};
tu=function(a,b){if(a)for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].indexOf("="),f=null,g=null;0<=e?(f=c[d].substring(0,e),g=c[d].substring(e+1)):f=c[d];b(f,g?(0,window.decodeURIComponent)(g.replace(/\+/g," ")):"")}};uu=function(a){return _.fd.concat.apply(_.fd,arguments)};
_.vu=function(a,b){this.J=this.O=this.I="";this.K=null;this.Y=this.U="";this.M=this.T=!1;var c;a instanceof _.vu?(this.M=_.ea(b)?b:a.M,_.wu(this,a.I),_.xu(this,a.O),_.yu(this,a.J),_.zu(this,a.K),this.setPath(a.getPath()),_.Au(this,a.G.clone()),this.N(a.S())):a&&(c=_.Ah(String(a)))?(this.M=!!b,_.wu(this,c[1]||"",!0),_.xu(this,c[2]||"",!0),_.yu(this,c[3]||"",!0),_.zu(this,c[4]),this.setPath(c[5]||"",!0),_.Au(this,c[6]||"",!0),this.N(c[7]||"",!0)):(this.M=!!b,this.G=new _.Bu(null,0,this.M))};
_.vu.prototype.toString=function(){var a=[],b=this.I;b&&a.push(Cu(b,Du,!0),":");if(b=this.J){a.push("//");var c=this.O;c&&a.push(Cu(c,Du,!0),"@");a.push(_.xh(b).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.K;null!=b&&a.push(":",String(b))}if(b=this.getPath())this.J&&"/"!=b.charAt(0)&&a.push("/"),a.push(Cu(b,"/"==b.charAt(0)?Eu:Fu,!0));(b=this.G.toString())&&a.push("?",b);(b=this.S())&&a.push("#",Cu(b,Gu));return a.join("")};
_.vu.prototype.resolve=function(a){var b=this.clone(),c=!!a.I;c?_.wu(b,a.I):c=!!a.O;c?_.xu(b,a.O):c=!!a.J;c?_.yu(b,a.J):c=null!=a.K;var d=a.getPath();if(c)_.zu(b,a.K);else if(c=!!a.U){if("/"!=d.charAt(0))if(this.J&&!this.U)d="/"+d;else{var e=b.getPath().lastIndexOf("/");-1!=e&&(d=b.getPath().substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){for(var d=_.$c(e,"/"),e=e.split("/"),f=[],g=0;g<e.length;){var k=e[g++];"."==k?d&&g==e.length&&f.push(""):".."==k?
((1<f.length||1==f.length&&""!=f[0])&&f.pop(),d&&g==e.length&&f.push("")):(f.push(k),d=!0)}d=f.join("/")}else d=e}c?b.setPath(d):c=""!==a.G.toString();c?_.Au(b,Hu(a.G.toString())):c=!!a.Y;c&&b.N(a.S());return b};_.vu.prototype.clone=function(){return new _.vu(this)};_.wu=function(a,b,c){_.Iu(a);a.I=c?Hu(b,!0):b;a.I&&(a.I=a.I.replace(/:$/,""));return a};_.xu=function(a,b,c){_.Iu(a);a.O=c?Hu(b):b;return a};_.yu=function(a,b,c){_.Iu(a);a.J=c?Hu(b,!0):b;return a};
_.zu=function(a,b){_.Iu(a);if(b){b=Number(b);if((0,window.isNaN)(b)||0>b)throw Error("N`"+b);a.K=b}else a.K=null;return a};_.vu.prototype.getPath=function(){return this.U};_.vu.prototype.setPath=function(a,b){_.Iu(this);this.U=b?Hu(a,!0):a;return this};_.Au=function(a,b,c){_.Iu(a);b instanceof _.Bu?(a.G=b,Ju(a.G,a.M)):(c||(b=Cu(b,Ku)),a.G=new _.Bu(b,0,a.M));return a};_.vu.prototype.Ta=function(a,b){return _.Au(this,a,b)};_.vu.prototype.Re=function(){return this.G.toString()};
_.Lu=function(a,b,c){_.Iu(a);a.G.set(b,c);return a};_.vu.prototype.Gd=function(a){return this.G.get(a)};_.vu.prototype.S=function(){return this.Y};_.vu.prototype.N=function(a,b){_.Iu(this);this.Y=b?Hu(a):a;return this};_.Iu=function(a){if(a.T)throw Error("O");};_.Mu=function(a){return a instanceof _.vu?a.clone():new _.vu(a,void 0)};Hu=function(a,b){return a?b?(0,window.decodeURI)(a.replace(/%25/g,"%2525")):(0,window.decodeURIComponent)(a):""};
Cu=function(a,b,c){return _.ka(a)?(a=(0,window.encodeURI)(a).replace(b,Nu),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null};Nu=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)};Du=/[#\/\?@]/g;Fu=/[\#\?:]/g;Eu=/[\#\?]/g;Ku=/[\#\?@]/g;Gu=/#/g;_.Bu=function(a,b,c){this.I=this.G=null;this.J=a||null;this.K=!!c};Ou=function(a){a.G||(a.G=new _.sf,a.I=0,a.J&&tu(a.J,function(b,c){a.add((0,window.decodeURIComponent)(b.replace(/\+/g," ")),c)}))};_.h=_.Bu.prototype;
_.h.ob=function(){Ou(this);return this.I};_.h.add=function(a,b){Ou(this);this.J=null;a=Pu(this,a);var c=this.G.get(a);c||this.G.set(a,c=[]);c.push(b);this.I++;return this};_.h.remove=function(a){Ou(this);a=Pu(this,a);return _.vf(this.G.I,a)?(this.J=null,this.I-=this.G.get(a).length,this.G.remove(a)):!1};_.h.clear=function(){this.G=this.J=null;this.I=0};_.h.isEmpty=function(){Ou(this);return 0==this.I};var Qu=function(a,b){Ou(a);b=Pu(a,b);return _.vf(a.G.I,b)};_.h=_.Bu.prototype;
_.h.Fh=function(a){var b=this.Gc();return _.nd(b,a)};_.h.qd=function(){Ou(this);for(var a=this.G.Gc(),b=this.G.qd(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};_.h.Gc=function(a){Ou(this);var b=[];if(_.ka(a))Qu(this,a)&&(b=uu(b,this.G.get(Pu(this,a))));else{a=this.G.Gc();for(var c=0;c<a.length;c++)b=uu(b,a[c])}return b};_.h.set=function(a,b){Ou(this);this.J=null;a=Pu(this,a);Qu(this,a)&&(this.I-=this.G.get(a).length);this.G.set(a,[b]);this.I++;return this};
_.h.get=function(a,b){var c=a?this.Gc(a):[];return 0<c.length?String(c[0]):b};_.Ru=function(a,b,c){a.remove(b);0<c.length&&(a.J=null,a.G.set(Pu(a,b),_.Id(c)),a.I+=c.length)};_.Bu.prototype.toString=function(){if(this.J)return this.J;if(!this.G)return"";for(var a=[],b=this.G.qd(),c=0;c<b.length;c++)for(var d=b[c],e=_.xh(d),d=this.Gc(d),f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+_.xh(d[f]));a.push(g)}return this.J=a.join("&")};
_.Bu.prototype.clone=function(){var a=new _.Bu;a.J=this.J;this.G&&(a.G=this.G.clone(),a.I=this.I);return a};var Pu=function(a,b){var c=String(b);a.K&&(c=c.toLowerCase());return c},Ju=function(a,b){b&&!a.K&&(Ou(a),a.J=null,a.G.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),_.Ru(this,e,a))},a));a.K=b};_.Bu.prototype.extend=function(a){for(var b=0;b<arguments.length;b++)_.of(arguments[b],function(a,b){this.add(b,a)},this)};

_.rM={s:function(a,b,c){return(0,window.isNaN)(c)||""==c||a.length>=c?a:a=-1<b.indexOf("-",0)?a+_.bd(" ",c-a.length):_.bd(" ",c-a.length)+a},f:function(a,b,c,d,e){d=a.toString();(0,window.isNaN)(e)||""==e||(d=(0,window.parseFloat)(a).toFixed(e));var f;f=0>a?"-":0<=b.indexOf("+")?"+":0<=b.indexOf(" ")?" ":"";0<=a&&(d=f+d);if((0,window.isNaN)(c)||d.length>=c)return d;d=(0,window.isNaN)(e)?Math.abs(a).toString():Math.abs(a).toFixed(e);a=c-d.length-f.length;return d=0<=b.indexOf("-",0)?f+d+_.bd(" ",a): f+_.bd(0<=b.indexOf("0",0)?"0":" ",a)+d},d:function(a,b,c,d,e,f,g,k){return _.rM.f((0,window.parseInt)(a,10),b,c,d,0,f,g,k)}};_.rM.i=_.rM.d;_.rM.u=_.rM.d;

var sM=function(a){a=_.Ff(a);_.Hd(a,function(b,c){_.Ek(c)&&(a[c]=b)});return a},tM=function(a,b){if(null==b)return b;var c=String(b);c.match(/^\/\/.*/)&&(c=("http:"==window.location.protocol?"http:":"https:")+c);c.match(/^\/([^\/].*)?$/)&&window.location.host&&String(window.location.protocol).match(/^https?:$/)&&(c=window.location.protocol+"//"+window.location.host+c);var d=c.match(/^(https?:)(\/\/)?(\/([^\/].*)?)?$/i);d&&window.location.host&&String(window.location.protocol).match(/^https?:$/)&&
(c=d[1]+"//"+window.location.host+(d[3]||""));c=c.replace(/^(https?:\/\/[^\/?#@]*)\/$/i,"$1");c=c.replace(/^(http:\/\/[-_a-z0-9.]+):0*80([\/?#].*)?$/i,"$1$2");c=c.replace(/^(https:\/\/[-_a-z0-9.]+):0*443([\/?#].*)?$/i,"$1$2");c.match(/^https?:\/\/[-_a-z0-9.]*[-_a-z][-_a-z0-9.]*$/i)&&(c=c.toLowerCase());d=_.E("client/rewrite");_.Xc(d)&&Object.prototype.hasOwnProperty.call(d,c)?c=String(d[c]||c):(c=c.replace(/^(https?):\/\/www\.googleapis\.com$/,"$1://content.googleapis.com"),c=c.replace(/^(https?):\/\/www-(googleapis-[-_a-z0-9]+\.[-_a-z0-9]+\.google\.com)$/,
"$1://content-$2"),c.match(/^https?:\/\/content(-[-_a-z0-9.]+)?\.googleapis\.com$/)||(c=c.replace(/^(https?):\/\/([-_a-z0-9]+(\.[-_a-z0-9]+)?\.googleapis\.com)$/,"$1://content-$2")));a&&(d=_.E("client/firstPartyRewrite"),_.Xc(d)&&Object.prototype.hasOwnProperty.call(d,c)?c=String(d[c]||c):(c=c.replace(/^(https?):\/\/content\.googleapis\.com$/,"$1://clients6.google.com"),c=c.replace(/^(https?):\/\/content-([-a-z0-9]+)\.([-a-z0-9]+)\.googleapis\.com$/,"$1://$2-googleapis.$3.google.com"),c=c.replace(/^(https?):\/\/content-([-a-z0-9]+)\.googleapis\.com$/,
"$1://$2.clients6.google.com"),c=c.replace(/^(https?):\/\/([-a-z0-9]+)-www-googleapis\.([-a-z0-9]+).google.com$/,"$1://content-googleapis-$2.$3.google.com")));return c},uM={error:{code:-1,message:"A network error occurred and the request could not be completed."}},vM=function(a){return new _.$f(function(b,c){c(a)})},wM=function(a){a=_.Ff(a);_.mb(a,function(b,c){_.ja(b)&&(a[c]=b.join(", "))});return a},xM=function(a,b,c){c||((c=_.E("googleapis.config/proxy"))&&(c=String(c).replace(/\/static\/proxy\.html$/,
"")||"/"),c=String(c||""));c||(c=_.E("googleapis.config/root"),b&&(c=_.E("googleapis.config/root-1p")||c),c=String(c||""));c=String(tM(b,c)||c);return a=_.Eh(c,a)},yM=function(a,b,c,d){_.Oh.call(this);this.mb=a;this.Hb=b;this.Oa=c;this.hb=d;this.N=null};_.u(yM,_.Oh);
yM.prototype.then=function(a){this.N||(this.N=(new _.$f(function(a,c){this.V("error",(0,_.t)(function(){c(zM(this))},this));this.V("success",(0,_.t)(function(){a(zM(this))},this));this.send(this.mb,this.Hb,this.Oa,this.hb)},this)).then(function(a){a.headers=sM(a.headers);return a},function(a){return a.status?(a.headers=sM(a.headers),vM(a)):vM({result:uM,body:'{"error":{"code":-1,"message":"A network error occurred and the request could not be completed."}}',headers:null,status:null,statusText:null})}));
return this.N.then.apply(this.N,arguments)};
var zM=function(a){var b,c=a.getStatus(),d=_.bi(a);204==c?b=!1:b=""==a.Zp()?(0,_.dc)(d):_.ci(a);for(var e={},f=a.getAllResponseHeaders().split("\r\n"),g=0;g<f.length;g++)if(!_.vh(f[g])){var k=_.Hh(f[g],": ",2);e[k[0]]=e[k[0]]?e[k[0]]+(", "+k[1]):k[1]}var l;try{l=2<_.$h(a)?a.G.statusText:""}catch(m){l=""}return{result:b,body:d,headers:e,status:c,statusText:l}},AM=function(a,b){for(var c=_.Uc(b),d=c?b:arguments,c=c?0:1;c<d.length&&(a=a[d[c]],_.ea(a));c++);return a},BM=function(a){var b=a.params||_.Ka();
a=_.Ff(b.headers)||{};var c=b.httpMethod||"GET",d=String(b.url||""),e=b.body||null,b=b.responseType||null,f=_.dk(a);delete a["X-Referer"];a=wM(a);a=new yM(d,c,e,a);a.ya=f;b&&(a.K=b);return a},CM=function(a,b){var c=a.params||_.Ka();c.url=c.path;var d=c.root,d=xM("/",_.dk(c.headers),d);d.match(/^(.*[^\/])?\/$/)&&(d=d.substr(0,d.length-1));c.root=d;a.params=c;_.mk.gg("makeHttpRequests",[a],b)},DM={"'":"\\'"},EM={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',
"\\":"\\\\"},FM=function(a,b){var c=function(a){a=_.Ff(a);delete a.result;a={gapiRequest:{data:a}};b&&b(a,(0,_.ac)(a))};BM(a).then(c,c)},GM=function(a){return new _.$f(function(b,c){var d=function(a){a&&a.gapiRequest?a=a.gapiRequest.data||a:c(a);a={result:204!=a.status&&(0,_.dc)(a.body),body:a.body,headers:a.headers||null,status:a.status||null,statusText:a.statusText||null};_.Fh(a.status)?b(a):c(a)};try{CM(a,d)}catch(e){c(e)}})},HM=function(a){var b;b=(a=AM(a,"params","headers"))&&_.Xc(a)?a:{};a=
"chrome-extension"==(_.Ah(window.location.href)[1]||null);b=_.dk(b);var c=!0,d=_.Nh(_.Lh);d&&_.ea(d.withCredentials)||(c=!1);return!(a&&b)&&c},IM=function(a){_.Df.call(this,a)};_.u(IM,_.Df);IM.prototype.name="gapi.client.Error";var JM=function(a,b){_.E("client/cors")&&HM(a)?FM(a,b):CM(a,b)},KM=function(a){if(!a||!_.Yc(a))throw new IM("Must provide a function.");this.J=null;this.K=a};KM.prototype.then=function(a,b,c){this.J||(this.J=this.K());return this.J.then(a,b,c)};
KM.prototype.An=function(a){this.J||(this.J=a)};
var LM=function(a){(0,window.isFinite)(a)&&(a=String(a));return _.ka(a)?/^\s*-?0x/i.test(a)?(0,window.parseInt)(a,16):(0,window.parseInt)(a,10):window.NaN},MM=function(a){a=String(a);if(a.quote)return a.quote();for(var b=['"'],c=0;c<a.length;c++){var d=a.charAt(c),e=d.charCodeAt(0),f=c+1,g;if(!(g=EM[d])){if(!(31<e&&127>e))if(d in DM)d=DM[d];else if(d in EM)d=DM[d]=EM[d];else{e=d;g=d.charCodeAt(0);if(31<g&&127>g)e=d;else{if(256>g){if(e="\\x",16>g||256<g)e+="0"}else e="\\u",4096>g&&(e+="0");e+=g.toString(16).toUpperCase()}d= DM[d]=e}g=d}b[f]=g}b.push('"');return b.join("")};
var NM=function(a){this.G={};for(var b=0;b<a.length;b++){var c=a[b];this.G[c.G]=c}},OM=function(a){a=_.sd(a.G);_.Mv(a,function(a,c){return a.G-c.G});return a};var PM=function(a,b){this.G=a;this.K=b.name;this.J=!!b.yV;this.I=b.Gp;this.M=b.type};var QM=function(){this.Hc={};this.I=this.vf().G;this.G=null},RM=function(a,b,c){c=c||a;for(var d in a.Hc){var e=Number(d);a.I[e]||b.call(c,e,a.Hc[d])}};_.h=QM.prototype;_.h.has=function(a){return null!=this.Hc[a.G]};_.h.get=function(a,b){var c=a.G,d=SM(this,c);return this.I[c].J?d[b||0]:d};_.h.set=function(a,b){TM(this,a.G,b)};_.h.add=function(a,b){UM(this,a.G,b)};_.h.clear=function(a){a=a.G;delete this.Hc[a];this.G&&delete this.G[a]};
_.h.equals=function(a){if(!a||this.constructor!=a.constructor)return!1;for(var b=OM(this.vf()),c=0;c<b.length;c++){var d=b[c],e=d.G;if(null!=this.Hc[e]!=(null!=a.Hc[e]))return!1;if(null!=this.Hc[e]){var f=11==d.I||10==d.I,g=SM(this,e),e=SM(a,e);if(d.J){if(g.length!=e.length)return!1;for(d=0;d<g.length;d++){var k=g[d],l=e[d];if(f?!k.equals(l):k!=l)return!1}}else if(f?!g.equals(e):g!=e)return!1}}return!0};
var VM=function(a,b){for(var c=OM(a.vf()),d=0;d<c.length;d++){var e=c[d],f=e.G;if(null!=b.Hc[f]){a.G&&delete a.G[e.G];var g=11==e.I||10==e.I;if(e.J)for(var e=SM(b,f)||[],k=0;k<e.length;k++)UM(a,f,g?e[k].clone():e[k]);else e=SM(b,f),g?(g=SM(a,f))?VM(g,e):TM(a,f,e.clone()):TM(a,f,e)}}};QM.prototype.clone=function(){var a=new this.constructor;a!=this&&(a.Hc={},a.G&&(a.G={}),VM(a,this));return a};
var SM=function(a,b){var c=a.Hc[b];return null==c?null:c},TM=function(a,b,c){a.Hc[b]=c;a.G&&(a.G[b]=c)},UM=function(a,b,c){a.Hc[b]||(a.Hc[b]=[]);a.Hc[b].push(c);a.G&&delete a.G[b]},WM=function(a){var b=[],c;for(c in a)0!=c&&b.push(new PM(c,a[c]));return new NM(b)};
var XM=function(){QM.call(this)},YM;_.u(XM,QM);var ZM=function(){QM.call(this)},$M;_.u(ZM,QM);XM.prototype.vf=function(){YM||(YM=WM({0:{name:"Version",qF:"buzz.channel.Version"},1:{name:"major_version",Gp:5,type:Number},2:{name:"minor_version",Gp:5,type:Number}}));return YM};XM.ctor=XM;XM.ctor.vf=XM.prototype.vf;ZM.prototype.vf=function(){$M||($M=WM({0:{name:"ProtocolVersion",qF:"buzz.channel.ProtocolVersion"},1:{name:"version",Gp:11,type:XM}}));return $M};ZM.ctor=ZM;ZM.ctor.vf=ZM.prototype.vf;
(function(){var a;return _.Rd?(a=/Windows NT ([0-9.]+)/,(a=a.exec(_.vd))?a[1]:"0"):_.Qd?(a=/10[_.][0-9_.]+/,(a=a.exec(_.vd))?a[0].replace(/_/g,"."):"10"):_.Td?(a=/Android\s+([^\);]+)(\)|;)/,(a=a.exec(_.vd))?a[1]:""):_.Ud||_.Vd?(a=/(?:iPhone|CPU)\s+OS\s+(\S+)/,(a=a.exec(_.vd))?a[1].replace(/_/g,"."):""):""})();
var aN=new ZM,bN=new XM;TM(bN,1,3);TM(bN,2,2);TM(aN,1,bN);var cN=new XM;TM(cN,1,3);TM(cN,2,2);var dN=new XM;TM(dN,1,3);TM(dN,2,2);var eN=function(){};var fN=function(a,b){this.G=!!b};_.u(fN,eN);
var jN=function(a,b,c){var d=OM(b.vf());(0,_.id)(d,function(a){if(b.has(a)){var d;d=a.G;d=b.I[d].J?null!=b.Hc[d]?b.Hc[d].length:0:null!=b.Hc[d]?1:0;for(var g=0;g<d;++g){c.append(a.K);11==a.I||10==a.I?(c.append(" {"),gN(c),c.G+=2):c.append(": ");hN(this,b.get(a,g),a,c);if(11==a.I||10==a.I)c.G-=2,c.append("}");gN(c)}}},a);RM(b,function(a,b){iN(this,a,b,c)},a)},iN=function(a,b,c,d){if(null!=c)if(_.ja(c))(0,_.id)(c,function(a){iN(this,b,a,d)},a);else{if(_.Xc(c)){d.append(b);d.append(" {");gN(d);d.G+=
2;if(c instanceof QM)jN(a,c,d);else for(var e in c){var f=LM(e);iN(a,f,c[e],d)}d.G-=2;d.append("}")}else _.ka(c)&&(c=MM(c)),d.append(b),d.append(": "),d.append(c.toString());gN(d)}},hN=function(a,b,c,d){switch(c.I){case 1:case 2:case 3:case 4:case 5:case 13:case 6:case 7:case 8:case 15:case 16:case 17:case 18:d.append(b);break;case 12:case 9:b=MM(b.toString());d.append(b);break;case 14:if(!a.G){var e=!1;_.Hd(c.M,function(a,c){a==b&&(d.append(c),e=!0)})}e&&!a.G||d.append(b.toString());break;case 10:case 11:jN(a,
b,d)}},kN=function(){this.G=0;this.I=[];this.J=!0};kN.prototype.toString=function(){return this.I.join("")};kN.prototype.append=function(a){if(this.J){for(var b=0;b<this.G;++b)this.I.push(" ");this.J=!1}this.I.push(a.toString())};var gN=function(a){a.I.push("\n");a.J=!0};
var lN=new fN;QM.prototype.toString=function(){var a=new kN;jN(lN,this,a);return a.toString()};new _.zf([1,2,3]);new _.zf([1,2]);new _.$e;var nN=function(){for(var a=10,b=mN,c=b.length,d="";0<a--;)d+=b.charAt(Math.floor(Math.random()*c));return d},mN="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";var oN=function(a){_.pe.call(this);this.wa=a||_.rs()};_.u(oN,_.pe);oN.prototype.pA=0;oN.prototype.ia=function(){return this.pA};oN.prototype.Ra=function(){return this.wa.Ra()};var pN=function(a,b){oN.call(this,b);this.G=a;this.Y=this.G.I().ppu;this.Fa=this.G.I().lpu;this.O=[]},qN,rN;_.u(pN,oN);_.h=pN.prototype;_.h.AJ=5;_.h.pA=4;_.h.jq=0;_.h.Ri=!1;_.h.Nd=!1;_.h.Ry=null;var sN=function(a){return"googlexpc_"+a.G.name+"_msg"},tN=function(a){return"googlexpc_"+a.G.name+"_ack"},uN=function(a){try{if(!a.wb()&&a.G.K())return a.G.O().frames||{}}catch(b){}return{}};
pN.prototype.connect=function(){if(!this.wb()&&this.G.K()){if(!this.Nd){var a=sN(this);this.J=vN(this,a);this.U=this.Ra().frames[a];a=tN(this);this.I=vN(this,a);this.N=this.Ra().frames[a];this.Nd=!0}if(wN(this,sN(this))&&wN(this,tN(this)))this.ha=new xN(this,uN(this)[sN(this)],(0,_.t)(this.ya,this)),this.T=new xN(this,uN(this)[tN(this)],(0,_.t)(this.Ca,this)),this.W();else{if(1==this.G.J())this.Ry||0<this.AJ--||(this.G.S(nN()),yN(this),this.Nd=!1,this.Ry=vN(this,"googlexpc_reconnect_"+this.G.name));
else if(0==this.G.J())for(var a=uN(this),b=a.length,c=0;c<b;c++){var d;try{a[c]&&a[c].name&&(d=a[c].name)}catch(e){}if(d){var f=d.split("_");if(3==f.length&&"googlexpc"==f[0]&&"reconnect"==f[1]){this.G.name=f[2];yN(this);this.Nd=!1;break}}}this.Ra().setTimeout((0,_.t)(this.connect,this),100)}}};
var vN=function(a,b){var c=window.document.createElement("IFRAME"),d=c.style;d.position="absolute";d.top="-10px";d.left="10px";d.width="1px";d.height="1px";c.id=c.name=b;c.src=a.Y+"#INITIAL";a.Ra().document.body.appendChild(c);return c},yN=function(a){a.J&&(a.J.parentNode.removeChild(a.J),a.J=null,a.U=null);a.I&&(a.I.parentNode.removeChild(a.I),a.I=null,a.N=null)},wN=function(a,b){try{var c=uN(a)[b];if(!c||0!=c.location.href.indexOf(a.Fa))return!1}catch(d){return!1}return!0};
pN.prototype.W=function(){var a=uN(this);a[tN(this)]&&a[sN(this)]?(this.Ya=new zN(this.Y,this.U),this.M=new zN(this.Y,this.N),this.Ra().setTimeout((0,_.t)(function(){this.Ya.send("SETUP");this.Ri=!0},this),100)):(this.ma||(this.ma=(0,_.t)(this.W,this)),this.Ra().setTimeout(this.ma,100))};var AN=function(a){if(a.la&&a.Oa&&(a.G.N(),a.K)){for(var b=0,c;b<a.K.length;b++)c=a.K[b],a.G.M(c.service,c.uJ);delete a.K}};
pN.prototype.ya=function(a){if("SETUP"==a)this.M&&(this.M.send("SETUP_ACK"),this.la=!0,AN(this));else if(this.G.G()||this.la){var b=a.indexOf("|"),c=a.substring(0,b);a=a.substring(b+1);b=c.indexOf(",");if(-1==b){var d;this.M.send("ACK:"+c);BN(this,a)}else d=c.substring(0,b),this.M.send("ACK:"+d),c=c.substring(b+1).split("/"),b=(0,window.parseInt)(c[0],10),c=(0,window.parseInt)(c[1],10),1==b&&(this.S=[]),this.S.push(a),b==c&&(BN(this,this.S.join("")),delete this.S)}};
pN.prototype.Ca=function(a){"SETUP_ACK"==a?(this.Ri=!1,this.Oa=!0,AN(this)):this.G.G()&&this.Ri&&(0,window.parseInt)(a.split(":")[1],10)==this.jq&&(this.Ri=!1,CN(this))};var CN=function(a){if(!a.Ri&&a.O.length){var b=a.O.shift();++a.jq;a.Ya.send(a.jq+b);a.Ri=!0}},BN=function(a,b){var c=b.indexOf(":"),d=b.substr(0,c),c=b.substring(c+1);a.G.G()?a.G.M(d,c):(a.K||(a.K=[])).push({service:d,uJ:c})};
pN.prototype.send=function(a,b){var c=a+":"+b;if(!_.N||3800>=b.length)this.O.push("|"+c);else for(var d=b.length,e=Math.ceil(d/3800),f=0,g=1;f<d;)this.O.push(","+g+"/"+e+"|"+c.substr(f,3800)),g++,f+=3800;CN(this)};pN.prototype.ja=function(){pN.R.ja.call(this);var a=DN;_.oe(a,this.ha);_.oe(a,this.T);this.ha=this.T=null;_.ah(this.J);_.ah(this.I);this.U=this.N=this.J=this.I=null};
var DN=[],EN=(0,_.t)(function(){var a=DN,b,c=!1;try{for(var d=0;b=a[d];d++)c=c||b.ln()}catch(e){if(b.K.G.U(),!a.length)return}a=(0,_.wa)();c&&(qN=a);rN=window.setTimeout(EN,1E3>a-qN?10:100)},pN),FN=function(){qN=(0,_.wa)();rN&&window.clearTimeout(rN);rN=window.setTimeout(EN,10)},zN=function(a,b){if(!/^https?:\/\//.test(a))throw Error("lb`"+a);this.J=a;this.I=b;this.G=0};
zN.prototype.send=function(a){this.G=++this.G%2;a=this.J+"#"+this.G+(0,window.encodeURIComponent)(a);try{_.Od?this.I.location.href=a:this.I.location.replace(a)}catch(b){}FN()};var xN=function(a,b,c){this.K=a;this.I=b;this.J=c;this.G=this.I.location.href.split("#")[0]+"#INITIAL";DN.push(this);FN()};xN.prototype.ln=function(){var a=this.I.location.href;if(a!=this.G){this.G=a;if(a=a.split("#")[1])a=a.substr(1),this.J((0,window.decodeURIComponent)(a));return!0}return!1};
var GN=function(a){this.J=a;this.K=!1;this.promise={then:(0,_.t)(function(a,c,d){this.K||(this.K=!0);this.I&&!this.G?this.J.resolve(this.I):this.G&&!this.I&&this.J.reject(this.G);return this.J.promise.then(a,c,d)},this)}};GN.prototype.resolve=function(a){this.K?this.J.resolve(a):this.I||this.G||(this.I=a)};GN.prototype.reject=function(a){this.K?this.J.reject(a):this.I||this.G||(this.G=a)};
var HN=function(a){KM.call(this,HN.prototype.M);if(!a||"object"!=typeof a&&"string"!=typeof a)throw new IM("Invalid request parameters");var b;_.ka(a)?b={path:a}:b=a;if(!b.path)throw new IM('Missing required parameter: "path"');this.G={path:b.path,method:b.method||"GET",params:b.params||{},headers:b.headers||{},body:b.body,root:b.root,responseType:b.responseType};this.I=b.authType||"auto"};_.u(HN,KM);HN.prototype.Xh=function(){return this.G};
HN.prototype.sk=function(){var a=this.G,b=a.headers||{},c=b,d=a.applicationName||null,e=a.clientName||null,f=a.clientVersion||null,f=f||"0.1",e=e||"google-api-javascript-client",g=[];d&&(g.push(d),g.push(" "));g.push(e);f&&(g.push("/"),g.push(f));c["X-JavaScript-User-Agent"]=g.join("");c=b["Content-Type"];a.body&&!c&&(c="application/json",b["Content-Type"]=c);"application/json"!=c||a.params.alt||(a.params.alt="json");(c=a.body||null)&&_.Xc(c)&&(a.body=(0,_.ac)(c));a.key=a.id;b=_.mk.$k(b,void 0,this.I);
c=_.dk(b);IN(b);(b=_.pk.key)&&!_.ea(a.params.key)&&(a.params.key=b);(b=String(a.path||"").match(/^(https?:\/\/[^\/?#]+)([\/?#].*)?$/i))&&!a.root&&(a.root=String(b[1]),a.path=String(b[2]||"/"),a.path.match(/^\/_ah\/api(\/.*)?$/)&&(a.root+="/_ah/api",a.path=a.path.substr(8)));b=a.params;d=_.Fk(a.path);e=String(_.E("googleapis.config/xd3")||"");18<=e.length&&"/static/proxy.html"==e.substring(e.length-18)&&(e=e.substring(0,e.length-18));e||(e="/");f=_.Fk(e);if(e!=f)throw Error("G");"/"!=e.charAt(e.length-
1)&&(e+="/");d=_.Eh(e,d);_.pd(d,"/")&&(d=d.substring(0,d.length-1));d=_.Bh(_.Dh([d],b));a.path=d;a.root=tM(c,a.root);a.url=xM(a.path,c,a.root)};var LN=function(a){a.sk();a=a.G;return{key:"gapiRequest",params:{id:a.id,key:a.key,url:a.url,path:a.path,httpMethod:a.method,body:a.body||"",headers:a.headers||{},urlParams:{},root:a.root,clientName:JN(),clientVersion:KN()}}};
HN.prototype.execute=function(a){this.G.headers.Authorization||_.Wj(void 0,void 0);var b=LN(this);JM(b,function(b,d){var e=b;b.gapiRequest&&(e=b.gapiRequest);e&&e.data&&(e=e.data);var e=e instanceof Array?e[0]:e,f;if(204!=e.status&&e.body)try{f=(0,_.dc)(e.body)}catch(g){}_.E("client/jsonpOverride")&&(f=e);a&&a(f,d)})};HN.prototype.M=function(){var a=LN(this);return _.E("client/cors")&&HM(a)?BM(a):GM(a)};
var MN=/<response-(.*)>/,NN=/^application\/http(;.+$|$)/,ON=function(a,b){if(!a||!b||!_.La(a,b=b.toLowerCase()))throw new IM("Unable to retrieve header.");return a[b]},RN=function(a,b){for(var c="batch"+String(Math.round(2147483647*(0,_.jk)()))+String(Math.round(2147483647*(0,_.jk)())),d={path:"/batch",headers:{"Content-Type":"multipart/mixed; boundary="+c},method:"POST"},c="--"+c,e=[],f=0;f<a.length;f++)e.push(PN(a[f].request,a[f].id));d.body=[c,e.join("\r\n"+c+"\r\n"),c+"--"].join("\r\n")+"\r\n";
d.root=b||null;return QN(d)},PN=function(a,b){var c=[],d=a.Xh(),e=function(a,b){_.mb(a,function(a,c){b.push(c+": "+a)})};e({"Content-Type":"application/http","Content-Transfer-Encoding":"binary","Content-ID":"<"+b+">"},c);c.push("");c.push(d.method+" "+d.path);e(d.headers,c);c.push("");d.body&&c.push(d.body);return c.join("\r\n")},TN=function(a,b){var c=SN(a,b),d={};_.Hd(c,function(a,b){d[b]={result:a.result||a.body,rawResult:(0,_.ac)({id:b,result:a.result||a.body}),id:b}});return d},SN=function(a,
b){a=(0,_.ad)(a);_.pd(a,"--")&&(a=a.substring(0,a.length-2));for(var c=a.split(b),d=_.Ka(),e=0;e<c.length;e++)if(c[e]){var f;if(f=c[e]){_.pd(f,"\r\n")&&(f=f.substring(0,f.length-2));f=UN(f);var g=_.Ka(),k=ON(f.outerHeaders,"Content-Type");if(null==NN.exec(k))throw new IM("Unexpected Content-Type");k=ON(f.outerHeaders,"Content-Id");k=MN.exec(k);if(!k)throw new IM("Unable to recognize Content-Id.");g.id=k[1];k=(0,_.dc)(f.body);g.response={result:k,body:f.body,status:f.status,statusText:f.statusText,
headers:f.headers};f=g}else f=null;f&&f.id&&(d[f.id]=f.response)}return d},UN=function(a){if(!a)return null;a=a.split("\r\n");for(var b=0,c={headers:{},body:""},d=function(a){var b=0;_.mb(a,function(){b++});return b};b<a.length&&""==a[b];)b++;c.outerHeaders=VN(a,b);var b=b+(d(c.outerHeaders)+1),e=a[b++].split(" ");c.status=Number(e[1]);c.statusText=e[2];c.headers=VN(a,b);b+=d(c.headers)+1;c.body=a.slice(b).join("\r\n");return c},VN=function(a,b){for(var c=_.Ka(),d=b;d<a.length&&a[d];d++){var e=a[d].split(": "), f=(0,_.ad)(e[0].toLowerCase()),e=(0,_.ad)(e[1]);c[f]=e}return c};
var WN=function(a){KM.call(this,WN.prototype.M);this.G=[];this.I=a;this.O=!!a};_.u(WN,KM);var XN=function(a,b){for(var c=0;c<a.G.length;c++)if(a.G[c].id==b)return!0;return!1};
WN.prototype.add=function(a,b){var c=b||_.Ka(),d=_.Ka();if(a)d.request=a;else throw new IM("Batch entry "+(_.La(c,"id")?'"'+c.id+'" ':"")+"is missing a request method");var e;e=_.Rm();e=new GN(e);d.pn=e;a.An(d.pn.promise);e=a.Xh().root;if(!this.O){if(e&&this.I&&e!=this.I)throw new IM('The "root" provided in this request is not consistent with that of existing requests in the batch.');this.I=e||this.I}if(_.La(c,"id")){e=c.id;if(XN(this,e))throw new IM('Batch ID "'+e+'" already in use, please use another.');
d.id=e}else{do d.id=String(Math.round(2147483647*(0,_.jk)()));while(XN(this,d.id))}d.Yb=c.callback;this.G.push(d);return d.id};WN.prototype.execute=function(a){1>this.G.length||(_.lb(this.G,function(a){a.request.sk()}),a=YN(this,a),RN(this.G,this.I).execute(a))};
WN.prototype.M=function(){if(1>this.G.length)return new _.$f(function(a){a({})});_.lb(this.G,function(a){a.request.sk()});var a=RN(this.G,this.I),b=(0,_.t)(function(a){ZN(a);if(0!=ON(a.headers,"Content-Type").indexOf("multipart/mixed"))throw new IM("The response's Content-Type is not multipart/mixed.");var b=ON(a.headers,"Content-Type").split("boundary=")[1];if(!b)throw new IM("Boundary not indicated in response.");b=SN(a.body,"--"+b);a.result=b||{};for(var c=0;c<this.G.length;c++){var g=this.G[c],
k=b[g.id];_.Fh(k.status)?g.pn.resolve(k):g.pn.reject(k)}return a},this),c=(0,_.t)(function(a){for(var b=0;b<this.G.length;b++)this.G[b].pn.reject({result:{error:{code:0,message:"The batch request could not be fulfilled."}},body:'{"error":{"code":0,"message":"The batch request could not befulfilled"}}',headers:null,status:null,statusText:null});throw a;},this);return a.then(b,c)};
var YN=function(a,b){return(0,_.t)(function(a,d){var e;e=a;if(d&&!e){var f=(0,_.dc)(d);f&&(f.gapiRequest?e=f.gapiRequest.data:e=f)}ZN(e);if(e){if(0!=ON(e.headers,"Content-Type").indexOf("multipart/mixed"))throw new IM("The response's Content-Type is not multipart/mixed.");if(200<=e.status&&299>=e.status){var g=ON(e.headers,"Content-Type").split("boundary=")[1];if(!g)throw new IM("Boundary not indicated in response.");g=TN(e.body,"--"+g);for(e=0;e<this.G.length;e++)if(f=this.G[e],delete g[f.id].rawResult, f.Yb){var k=(0,_.ac)(g[f.id]);f.Yb(g[f.id]||!1,k)}}b&&b(g||null,d)}},a)},ZN=function(a){if(a&&a.headers){var b=_.Ka(),c;for(c in a.headers)b[c.toLowerCase()]=a.headers[c];a.headers=b}};
var $N=["appVersion","platform","userAgent"],aO={"google-api-javascript-client":!0,"google-api-gwt-client":!0},bO={},cO=function(a,b){var c;return c="/discovery/v1/apis/"+((0,window.encodeURIComponent)(a)+"/"+(0,window.encodeURIComponent)(b)+"/rpc?fields=methods%2F*%2Fid&pp=0")},dO=function(a,b){var c;return c="/discovery/v1/apis/"+((0,window.encodeURIComponent)(a)+"/"+(0,window.encodeURIComponent)(b)+"/rest?fields=rootUrl%2CservicePath%2Cresources%2Cparameters%2Cmethods&pp=0")},IN=function(a){if(a&&
window.navigator){for(var b=[],c=0;c<$N.length;c++){var d=window.navigator[$N[c]];d&&b.push((0,window.encodeURIComponent)($N[c])+"="+(0,window.encodeURIComponent)(d))}a["X-ClientDetails"]=b.join("&")}},JN=function(){var a=_.E("client/name","google-api-javascript-client");return a in aO?a:"google-api-javascript-client"},KN=function(){return String(_.E("client/version","1.1.0-beta"))},gO=function(a,b,c,d){if(!a||!b)throw new IM("Missing required parameters.");var e=c||function(){};QN({path:cO(a,b),
callback:function(a){if(a.error)e(a);else{var c=null!=a.rootUrl?String(a.rootUrl):d,c=_.ka(c)?c.replace(/([^\/])\/$/,"$1"):void 0,k;for(k in a)if(a.hasOwnProperty(k)&&"methods"==k){var l=a[k],m;for(m in l)if(l.hasOwnProperty(m)){eO(m,{root:c},void 0);var n={};n[m]=b;fO(n)}}e.call(null)}},root:d})},iO=function(a,b,c,d){function e(a){function b(a){_.mb(a,function(a){hO(g,a,w,e)})}function c(a){_.mb(a,function(a){b(a.methods);(a=a.resources)&&c(a)})}if(a.error)k(a);else{var e=_.Ff(_.Xc(d)?d:{}),f=e.root,
f=null!=a.rootUrl?String(a.rootUrl):f,f=_.ka(f)?f.replace(/([^\/])\/$/,"$1"):void 0;e.root=f;var g=a.servicePath,w=a.parameters;(f=a.resources)&&c(f);(a=a.methods)&&b(a);k.call()}}var f,g;_.Xc(a)?(g=a,f=a.name,b=a.version):f=a;if(!f||!b)throw new IM("Missing required parameters.");var k=c||function(){};g?e(g):QN({path:dO(f,b),callback:e,root:d&&d.root})},QN=function(a,b){var c;"object"==typeof a&&(c=a.callback,delete a.callback);var d;jO()?d=new kO(a,b):d=new HN(a);return c?(d.execute(c),null):d},
lO=function(a,b){b=_.Ff(b);var c=function(a,b,c){var d;if(a.hasOwnProperty(b))d=a[b],delete a[b];else if(c)throw new IM("Missing required parameters.");return d},d=c(b,"servicePath",!0),e=String(c(b,"restPath",!0)),f=String(c(b,"httpMethod",!0)),g=c(b,"parameters");null!=g?g=_.Ff(g):g=null;var k=c(b,"parameterName");_.ka(k)||(k=null);c=c(b,"supportsSubscription");if(!e||!f)throw new IM("Missing required parameters.");e={id:a,path:e,parameters:g,httpMethod:f,request:{parameterName:k}};c&&(e.supportsSubscription=
c);hO(d,e,{path:{},query:{}},b)},eO=function(a,b,c){if(!a)throw new IM("Missing required parameters");for(var d=a.split("."),e=window.gapi.client,f=0;f<d.length-1;f++){var g=d[f];e[g]=e[g]||{};e=e[g]}d=d[d.length-1];if(!e[d]||c){var k=b||{};e[d]=function(b){var c;"string"==typeof k?c=k:c=k.root;b&&b.root&&(c=b.root);b={method:a,apiVersion:k.apiVersion,rpcParams:b,transport:{name:"googleapis",root:c}};return jO()?new kO(b,2):new mO(b)}}},hO=function(a,b,c,d){if(!(b&&b.id&&b.path&&b.httpMethod))throw new IM("Missing required parameters");
var e=b.id.split("."),f=window.gapi.client,g;for(g=0;g<e.length-1;g++){var k=e[g];f[k]=f[k]||{};f=f[k]}k=window.gapi.client[e[0]];k.Os||(k.Os={servicePath:a||"",parameters:c});a=e[g];if(!f[a]){if(d&&d.hasOwnProperty("root"))var l=d.root;f[a]=_.va(nO,{path:_.ka(b.path)?b.path:null,httpMethod:_.ka(b.httpMethod)?b.httpMethod:null,parameters:b.parameters,parameterName:(b.request||{}).parameterName||"",request:b.request,root:l},k.Os)}},nO=function(a,b,c,d){var e=b.servicePath||"";_.$c(e,"/")||(e="/"+e);
c=oO(a.path,[a.parameters,b.parameters],c||{});b=c.dg;var f=c.DL,e=_.Eh(e,c.path);c=f.root;delete f.root;var g=a.parameterName;!g&&1==_.wf(f)&&f.hasOwnProperty("resource")&&(g="resource");var k;g&&(k=f[g],delete f[g]);null!=k||(k=d);null==k&&a.request&&(_.Gf(f)&&(f=void 0),k=f);d="complete"==_.E("client/rms")?0:1;f={};g=a.httpMethod;"GET"==g&&_.ea(k)&&""!=String(k)&&(f["X-HTTP-Method-Override"]=g,g="POST");return QN({path:e,method:g,params:b,headers:f,body:k,root:c||a.root},d)||null},oO=function(a,
b,c){c=_.Ff(c);var d={};_.lb(b,function(b){_.mb(b,function(b,e){var k=b.required;if("path"==b.location)if(Object.prototype.hasOwnProperty.call(c,e))-1!=a.indexOf("{"+e+"}")?(k=_.xh(c[e]),a=a.replace("{"+e+"}",k)):-1!=a.indexOf("{+"+e+"}")&&(k=(0,window.encodeURI)(String(c[e])),a=a.replace("{+"+e+"}",k)),delete c[e];else{if(k)throw new IM("Required path parameter "+e+" is missing.");}else"query"==b.location&&Object.prototype.hasOwnProperty.call(c,e)&&(d[e]=c[e],delete c[e])})});if(b=c.trace)d.trace=
b,delete c.trace;return{path:a,dg:d,DL:c}},qO=function(a){return jO()?new pO(a,0):new WN(a)},fO=function(a){_.tk(a);for(var b in a)Object.prototype.hasOwnProperty.call(a,b)&&(bO[b]=a[b])};_.uk(null);var rO=function(a){var b=["complete"],c=_.E("client/rms");if(_.nd(["rpcDeprecated","migrated"],c))_.Sb(a+" is deprecated. See https://developers.google.com/api-client-library/javascript/reference/referencedocs");else if(_.nd(b,c))throw new IM(a+" is discontinued.");},jO=function(){return"migrated"==_.E("client/rms")};
var sO=function(){this.G=[];this.J=this.I=null};sO.prototype.add=function(a,b){var c=b||{},d={},e=Object.prototype.hasOwnProperty;if(a)d.hh=a;else throw new IM("Batch entry "+(e.call(c,"id")?'"'+c.id+'" ':"")+"is missing a request method");if(e.call(c,"id")){for(var e=c.id,f=0;f<this.G.length;f++)if(this.G[f].id==e)throw new IM('Batch ID "'+e+'" already in use, please use another.');d.id=e}else{do d.id=String(2147483647*(0,_.jk)()|0);while(e.call(this.G,d.id))}d.Yb=c.callback;this.G.push(d)};
sO.prototype.execute=function(a){this.I=[];for(var b,c,d=0;d<this.G.length;d++)b=this.G[d],c=b.hh,this.I.push(c.Sm(b.id)),this.J=c.em()||this.J;b={};b=_.mk.$k(b);IN(b);b={requests:this.I,headers:b,root:this.J,clientName:JN(),clientVersion:KN(),urlParams:{key:_.pk.key}};_.mk.gg("makeRequest",b,tO(this,a))};var tO=function(a,b){return function(c,d){for(var e=0;e<a.G.length;e++){var f=a.G[e];f.Yb&&f.Yb(c[f.id]||!1,d)}b&&b(c,d)}};
var mO=function(a){if(!a||"object"!=typeof a)throw new IM("Missing rpc parameters");if(!a.method)throw new IM("Missing rpc method");this.G=a};mO.prototype.em=function(){var a=this.G.transport;return a?a.root||null:null};mO.prototype.execute=function(a){var b=new sO;b.add(this,{id:"gapiRpc",callback:uO(a)});b.execute()};mO.prototype.Sm=function(a){var b=this.G.method;a={jsonrpc:"2.0",id:a,method:b,apiVersion:String(this.G.apiVersion||bO[b]||"v1")};(b=this.G.rpcParams)&&(a.params=b);return a}; var uO=function(a){return function(b,c){var d;b?b.error?(d=b.error,null==d.error&&(d.error=_.Ff(b.error))):(d=b.result||b.data,_.Xc(d)&&null==d.result&&(d.result=_.Ff(b.result||b.data))):d=!1;a(d,c)}};
var kO=function(a,b){this.I=b||0;if(2==this.I){var c=null;null!=a&&_.Xc(a)&&(c={method:a.method,rpcParams:a.rpcParams,transport:a.transport,root:a.root,apiVersion:a.apiVersion,authType:a.authType});this.G=new mO(c)}else 0==this.I&&(c=a&&a.callback)&&(a.callback=vO(c)),c=null,null!=a&&(_.Xc(a)?c={path:a.path,method:a.method,params:a.params,headers:a.headers,body:a.body,root:a.root,responseType:a.responseType,authType:a.authType}:_.ka(a)&&(c=a)),this.G=new HN(c)},vO=function(a){return function(b){var c;
null!=b&&_.Xc(b)&&b.error?(c=wO(b),b=(0,_.ac)([{id:"gapiRpc",error:c}]),c.error=_.zs(c)):(null!=b||(b={}),c=_.zs(b),c.result=_.zs(b),b=(0,_.ac)([{id:"gapiRpc",result:b}]));a(c,b)}},wO=function(a){a=_.zs(a.error);return{code:a.code,data:a.errors,message:a.message}};_.h=kO.prototype;_.h.execute=function(a){var b;a&&1==this.I?b=vO(a):b=a;this.G.execute(b)};_.h.then=function(a,b,c){2==this.I&&xO('The "then" method is not available on this object.');return this.G.then(a,b,c)};
_.h.An=function(a){this.G.An&&this.G.An(a)};_.h.Xh=function(){if(this.G.Xh)return this.G.Xh()};_.h.sk=function(){this.G.Xh&&this.G.sk()};_.h.em=function(){if(this.G.em)return this.G.em()};_.h.Sm=function(a){if(this.G.Sm)return this.G.Sm(a)};var pO=function(a,b){this.J=a;this.G=b||null;this.I=null};
pO.prototype.add=function(a,b){null===this.G&&(this.G=a.I,2==this.G?this.I=new sO:this.I=new WN(this.J));this.G!==a.I&&xO("Unable to add item to batch.");var c=b&&b.callback;1==this.G&&c&&(b.callback=function(a){a=yO(a);var b=(0,_.ac)([a]);c(a,b)});this.I.add(a,b)};pO.prototype.execute=function(a){var b;a&&1==this.G?b=function(b){var d=[];_.mb(b,function(a,e){a=yO(a);b[e]=a;d.push(a)});var e=(0,_.ac)(d);a(b,e)}:b=a;this.I&&this.I.execute(b)};
var yO=function(a){var b=a?AM(a,"result"):null;_.Xc(b)&&null!=b.error&&(b=wO(b),a={id:a.id,error:b});return a};pO.prototype.then=function(a,b,c){2==this.G&&xO('The "then" method is not available on this object.');return this.I.then(a,b,c)};var xO=function(a){throw Error("mb`"+a);};
_.D("gapi.client.load",function(a,b,c,d){function e(c){var d="migrated"==k||"complete"==k;_.Xc(a)&&(d="discovery#rpcDescription"!=a.kind);d?iO(a,b,c,g):_.ka(a)&&gO(a,b,c,f)}var f=_.Xc(d)?d.root:d,g=_.Xc(d)?d:{root:f},k=_.E("client/rms");if(c)e(c);else return new _.$f(function(a,b){try{e(a)}catch(c){b(c)}})});_.D("gapi.client.newBatch",function(a){return jO()?new pO(a):"complete"==_.E("client/rms")?qO(a):new sO});
_.D("gapi.client.newRpcBatch",function(){rO("gapi.client.newRpcBatch");return jO()?new pO:new sO});_.D("gapi.client.newHttpBatch",qO);_.D("gapi.client.register",function(a,b){if("complete"==_.E("client/rms"))lO(a,b);else{var c;b&&(c={apiVersion:b.apiVersion,root:b.root});eO(a,c)}});_.D("gapi.client.request",QN);
_.D("gapi.client.rpcRequest",function(a,b,c){rO("gapi.client.rpcRequest");if(!a)throw new IM('Missing required parameter "method".');a={method:a,apiVersion:b,rpcParams:c,transport:{name:"googleapis",root:c&&c.root||""}};return jO()?new kO(a,2):new mO(a)});_.D("gapi.client.setApiKey",_.uk);_.D("gapi.client.setApiVersions",fO);_.D("gapi.client.AuthType",{gM:"auto",NONE:"none",zQ:"oauth2",DO:"1p"});_.D("gapi.client.AuthType.AUTO","auto");_.D("gapi.client.AuthType.NONE","none"); _.D("gapi.client.AuthType.OAUTH2","oauth2");_.D("gapi.client.AuthType.FIRST_PARTY","1p");

});
// Google Inc.
